// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module synth_top_writeResult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        example_0_id_address0,
        example_0_id_ce0,
        example_0_id_q0,
        example_1_id_address0,
        example_1_id_ce0,
        example_1_id_q0,
        example_2_id_address0,
        example_2_id_ce0,
        example_2_id_q0,
        example_3_id_address0,
        example_3_id_ce0,
        example_3_id_q0,
        example_0_value_address0,
        example_0_value_ce0,
        example_0_value_q0,
        example_1_value_address0,
        example_1_value_ce0,
        example_1_value_q0,
        example_2_value_address0,
        example_2_value_ce0,
        example_2_value_q0,
        example_3_value_address0,
        example_3_value_ce0,
        example_3_value_q0,
        sv_0_id_address0,
        sv_0_id_ce0,
        sv_0_id_q0,
        sv_1_id_address0,
        sv_1_id_ce0,
        sv_1_id_q0,
        sv_2_id_address0,
        sv_2_id_ce0,
        sv_2_id_q0,
        sv_3_id_address0,
        sv_3_id_ce0,
        sv_3_id_q0,
        sv_0_value_address0,
        sv_0_value_ce0,
        sv_0_value_q0,
        sv_1_value_address0,
        sv_1_value_ce0,
        sv_1_value_q0,
        sv_2_value_address0,
        sv_2_value_ce0,
        sv_2_value_q0,
        sv_3_value_address0,
        sv_3_value_ce0,
        sv_3_value_q0,
        lambda_address0,
        lambda_ce0,
        lambda_q0,
        svNonZeroFeature_address0,
        svNonZeroFeature_ce0,
        svNonZeroFeature_q0,
        nonZeroFeature_address0,
        nonZeroFeature_ce0,
        nonZeroFeature_q0,
        weight_address0,
        weight_ce0,
        weight_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        output_r_q0,
        kernelType
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 20'b1;
parameter    ap_ST_st2_fsm_1 = 20'b10;
parameter    ap_ST_st3_fsm_2 = 20'b100;
parameter    ap_ST_st4_fsm_3 = 20'b1000;
parameter    ap_ST_st5_fsm_4 = 20'b10000;
parameter    ap_ST_st6_fsm_5 = 20'b100000;
parameter    ap_ST_st7_fsm_6 = 20'b1000000;
parameter    ap_ST_st8_fsm_7 = 20'b10000000;
parameter    ap_ST_st9_fsm_8 = 20'b100000000;
parameter    ap_ST_st10_fsm_9 = 20'b1000000000;
parameter    ap_ST_st11_fsm_10 = 20'b10000000000;
parameter    ap_ST_st12_fsm_11 = 20'b100000000000;
parameter    ap_ST_st13_fsm_12 = 20'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 20'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 20'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 20'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 20'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 20'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 20'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 20'b10000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv6_33 = 6'b110011;
parameter    ap_const_lv13_32 = 13'b110010;
parameter    ap_const_lv32_33 = 32'b110011;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [9:0] example_0_id_address0;
output   example_0_id_ce0;
input  [31:0] example_0_id_q0;
output  [9:0] example_1_id_address0;
output   example_1_id_ce0;
input  [31:0] example_1_id_q0;
output  [9:0] example_2_id_address0;
output   example_2_id_ce0;
input  [31:0] example_2_id_q0;
output  [9:0] example_3_id_address0;
output   example_3_id_ce0;
input  [31:0] example_3_id_q0;
output  [9:0] example_0_value_address0;
output   example_0_value_ce0;
input  [63:0] example_0_value_q0;
output  [9:0] example_1_value_address0;
output   example_1_value_ce0;
input  [63:0] example_1_value_q0;
output  [9:0] example_2_value_address0;
output   example_2_value_ce0;
input  [63:0] example_2_value_q0;
output  [9:0] example_3_value_address0;
output   example_3_value_ce0;
input  [63:0] example_3_value_q0;
output  [9:0] sv_0_id_address0;
output   sv_0_id_ce0;
input  [31:0] sv_0_id_q0;
output  [9:0] sv_1_id_address0;
output   sv_1_id_ce0;
input  [31:0] sv_1_id_q0;
output  [9:0] sv_2_id_address0;
output   sv_2_id_ce0;
input  [31:0] sv_2_id_q0;
output  [9:0] sv_3_id_address0;
output   sv_3_id_ce0;
input  [31:0] sv_3_id_q0;
output  [9:0] sv_0_value_address0;
output   sv_0_value_ce0;
input  [63:0] sv_0_value_q0;
output  [9:0] sv_1_value_address0;
output   sv_1_value_ce0;
input  [63:0] sv_1_value_q0;
output  [9:0] sv_2_value_address0;
output   sv_2_value_ce0;
input  [63:0] sv_2_value_q0;
output  [9:0] sv_3_value_address0;
output   sv_3_value_ce0;
input  [63:0] sv_3_value_q0;
output  [5:0] lambda_address0;
output   lambda_ce0;
input  [63:0] lambda_q0;
output  [5:0] svNonZeroFeature_address0;
output   svNonZeroFeature_ce0;
input  [31:0] svNonZeroFeature_q0;
output  [5:0] nonZeroFeature_address0;
output   nonZeroFeature_ce0;
input  [31:0] nonZeroFeature_q0;
output  [5:0] weight_address0;
output   weight_ce0;
input  [63:0] weight_q0;
output  [5:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [63:0] output_r_d0;
input  [63:0] output_r_q0;
input  [31:0] kernelType;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] example_0_id_address0;
reg example_0_id_ce0;
reg[9:0] example_1_id_address0;
reg example_1_id_ce0;
reg[9:0] example_2_id_address0;
reg example_2_id_ce0;
reg[9:0] example_3_id_address0;
reg example_3_id_ce0;
reg[9:0] example_0_value_address0;
reg example_0_value_ce0;
reg[9:0] example_1_value_address0;
reg example_1_value_ce0;
reg[9:0] example_2_value_address0;
reg example_2_value_ce0;
reg[9:0] example_3_value_address0;
reg example_3_value_ce0;
reg sv_0_id_ce0;
reg sv_1_id_ce0;
reg sv_2_id_ce0;
reg sv_3_id_ce0;
reg sv_0_value_ce0;
reg sv_1_value_ce0;
reg sv_2_value_ce0;
reg sv_3_value_ce0;
reg lambda_ce0;
reg svNonZeroFeature_ce0;
reg[5:0] nonZeroFeature_address0;
reg nonZeroFeature_ce0;
reg weight_ce0;
reg[5:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[63:0] output_r_d0;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm = 20'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_39;
wire   [0:0] tmp_fu_444_p2;
reg   [0:0] tmp_reg_673;
reg    ap_sig_bdd_159;
wire   [0:0] tmp_1_fu_450_p2;
reg   [0:0] tmp_1_reg_677;
wire   [63:0] tmp_i_fu_462_p1;
reg   [63:0] tmp_i_reg_684;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_174;
wire    grp_synth_top_classifyPoly_fu_383_ap_done;
wire   [0:0] exitcond_i_fu_456_p2;
reg   [31:0] nonZeroFeature_load_reg_694;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_198;
wire   [0:0] tmp_i1_fu_467_p2;
reg   [0:0] tmp_i1_reg_699;
wire   [32:0] tmp_24_i_cast3_fu_483_p1;
reg   [32:0] tmp_24_i_cast3_reg_703;
wire   [1:0] tmp_4_fu_513_p1;
reg   [1:0] tmp_4_reg_711;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_213;
wire   [0:0] tmp_i_44_fu_498_p2;
wire   [5:0] i_fu_539_p2;
reg   [5:0] i_reg_758;
wire   [31:0] a2_fu_576_p3;
reg   [31:0] a2_reg_763;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_249;
wire   [63:0] y_value_load_phi_i_fu_605_p3;
reg   [63:0] y_value_load_phi_i_reg_774;
wire   [0:0] tmp_27_i_fu_613_p2;
reg   [0:0] tmp_27_i_reg_779;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_262;
reg   [63:0] weight_load_reg_784;
wire   [31:0] p1_2_fu_651_p3;
reg   [31:0] p1_2_reg_789;
wire   [31:0] p2_2_fu_659_p3;
reg   [31:0] p2_2_reg_794;
wire   [63:0] grp_fu_440_p2;
reg   [63:0] tmp_30_i_reg_799;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_276;
wire   [63:0] grp_fu_435_p2;
reg   [63:0] dot_reg_804;
reg    ap_sig_cseq_ST_st17_fsm_16;
reg    ap_sig_bdd_288;
wire   [63:0] dot_1_fu_667_p3;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_bdd_298;
wire   [31:0] temp_fu_427_p1;
reg   [31:0] temp_reg_814;
reg    ap_sig_cseq_ST_st19_fsm_18;
reg    ap_sig_bdd_307;
wire    grp_synth_top_classifyPoly_fu_383_ap_start;
wire    grp_synth_top_classifyPoly_fu_383_ap_idle;
wire    grp_synth_top_classifyPoly_fu_383_ap_ready;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_example_0_id_address0;
wire    grp_synth_top_classifyPoly_fu_383_example_0_id_ce0;
wire   [31:0] grp_synth_top_classifyPoly_fu_383_example_0_id_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_example_1_id_address0;
wire    grp_synth_top_classifyPoly_fu_383_example_1_id_ce0;
wire   [31:0] grp_synth_top_classifyPoly_fu_383_example_1_id_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_example_2_id_address0;
wire    grp_synth_top_classifyPoly_fu_383_example_2_id_ce0;
wire   [31:0] grp_synth_top_classifyPoly_fu_383_example_2_id_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_example_3_id_address0;
wire    grp_synth_top_classifyPoly_fu_383_example_3_id_ce0;
wire   [31:0] grp_synth_top_classifyPoly_fu_383_example_3_id_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_example_0_value_address0;
wire    grp_synth_top_classifyPoly_fu_383_example_0_value_ce0;
wire   [63:0] grp_synth_top_classifyPoly_fu_383_example_0_value_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_example_1_value_address0;
wire    grp_synth_top_classifyPoly_fu_383_example_1_value_ce0;
wire   [63:0] grp_synth_top_classifyPoly_fu_383_example_1_value_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_example_2_value_address0;
wire    grp_synth_top_classifyPoly_fu_383_example_2_value_ce0;
wire   [63:0] grp_synth_top_classifyPoly_fu_383_example_2_value_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_example_3_value_address0;
wire    grp_synth_top_classifyPoly_fu_383_example_3_value_ce0;
wire   [63:0] grp_synth_top_classifyPoly_fu_383_example_3_value_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_sv_0_id_address0;
wire    grp_synth_top_classifyPoly_fu_383_sv_0_id_ce0;
wire   [31:0] grp_synth_top_classifyPoly_fu_383_sv_0_id_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_sv_1_id_address0;
wire    grp_synth_top_classifyPoly_fu_383_sv_1_id_ce0;
wire   [31:0] grp_synth_top_classifyPoly_fu_383_sv_1_id_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_sv_2_id_address0;
wire    grp_synth_top_classifyPoly_fu_383_sv_2_id_ce0;
wire   [31:0] grp_synth_top_classifyPoly_fu_383_sv_2_id_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_sv_3_id_address0;
wire    grp_synth_top_classifyPoly_fu_383_sv_3_id_ce0;
wire   [31:0] grp_synth_top_classifyPoly_fu_383_sv_3_id_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_sv_0_value_address0;
wire    grp_synth_top_classifyPoly_fu_383_sv_0_value_ce0;
wire   [63:0] grp_synth_top_classifyPoly_fu_383_sv_0_value_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_sv_1_value_address0;
wire    grp_synth_top_classifyPoly_fu_383_sv_1_value_ce0;
wire   [63:0] grp_synth_top_classifyPoly_fu_383_sv_1_value_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_sv_2_value_address0;
wire    grp_synth_top_classifyPoly_fu_383_sv_2_value_ce0;
wire   [63:0] grp_synth_top_classifyPoly_fu_383_sv_2_value_q0;
wire   [9:0] grp_synth_top_classifyPoly_fu_383_sv_3_value_address0;
wire    grp_synth_top_classifyPoly_fu_383_sv_3_value_ce0;
wire   [63:0] grp_synth_top_classifyPoly_fu_383_sv_3_value_q0;
wire   [5:0] grp_synth_top_classifyPoly_fu_383_lambda_address0;
wire    grp_synth_top_classifyPoly_fu_383_lambda_ce0;
wire   [63:0] grp_synth_top_classifyPoly_fu_383_lambda_q0;
wire   [5:0] grp_synth_top_classifyPoly_fu_383_svNonZeroFeature_address0;
wire    grp_synth_top_classifyPoly_fu_383_svNonZeroFeature_ce0;
wire   [31:0] grp_synth_top_classifyPoly_fu_383_svNonZeroFeature_q0;
wire   [5:0] grp_synth_top_classifyPoly_fu_383_nonZeroFeature_address0;
wire    grp_synth_top_classifyPoly_fu_383_nonZeroFeature_ce0;
wire   [31:0] grp_synth_top_classifyPoly_fu_383_nonZeroFeature_q0;
wire   [5:0] grp_synth_top_classifyPoly_fu_383_output_r_address0;
wire    grp_synth_top_classifyPoly_fu_383_output_r_ce0;
wire    grp_synth_top_classifyPoly_fu_383_output_r_we0;
wire   [63:0] grp_synth_top_classifyPoly_fu_383_output_r_d0;
wire   [63:0] grp_synth_top_classifyPoly_fu_383_output_r_q0;
reg   [5:0] yindex_assign_reg_322;
reg    ap_sig_cseq_ST_st20_fsm_19;
reg    ap_sig_bdd_383;
reg   [31:0] p1_i_reg_334;
reg   [31:0] p2_i_reg_346;
reg   [63:0] dot_i_reg_358;
reg   [63:0] p_0_i_reg_370;
reg    grp_synth_top_classifyPoly_fu_383_ap_start_ap_start_reg = 1'b0;
wire  signed [63:0] tmp_2_fu_527_p1;
wire  signed [63:0] tmp_28_i_fu_584_p1;
wire   [63:0] tmp_4_i_fu_431_p1;
wire   [63:0] temp_fu_427_p0;
wire   [31:0] tmp_4_i_fu_431_p0;
wire   [63:0] grp_fu_435_p0;
wire   [63:0] grp_fu_435_p1;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_bdd_424;
wire   [63:0] grp_fu_440_p0;
wire   [63:0] grp_fu_440_p1;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_433;
wire   [5:0] tmp_24_i_fu_477_p0;
wire   [12:0] tmp_24_i_fu_477_p2;
wire   [0:0] tmp_25_i_fu_487_p2;
wire   [0:0] not_i_fu_492_p2;
wire  signed [32:0] tmp_27_cast_i_cast_fu_504_p1;
wire  signed [32:0] sum_i_fu_508_p2;
wire   [4:0] tmp_3_fu_517_p4;
wire   [0:0] sel_tmp_i_fu_545_p2;
wire   [0:0] sel_tmp2_i_fu_558_p2;
wire   [31:0] sel_tmp1_i_fu_550_p3;
wire   [0:0] sel_tmp4_i_fu_571_p2;
wire   [31:0] sel_tmp3_i_fu_563_p3;
wire   [63:0] sel_tmp7_i_fu_589_p3;
wire   [63:0] sel_tmp9_i_fu_597_p3;
wire   [0:0] tmp_29_i2_fu_618_p2;
wire   [31:0] p1_fu_629_p2;
wire   [31:0] p2_fu_623_p2;
wire   [31:0] p1_1_fu_635_p3;
wire   [31:0] p2_1_fu_643_p3;
wire    grp_fu_435_ce;
wire    grp_fu_440_ce;
reg   [19:0] ap_NS_fsm;
wire   [12:0] tmp_24_i_fu_477_p00;
reg    ap_sig_bdd_180;


synth_top_classifyPoly grp_synth_top_classifyPoly_fu_383(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_synth_top_classifyPoly_fu_383_ap_start ),
    .ap_done( grp_synth_top_classifyPoly_fu_383_ap_done ),
    .ap_idle( grp_synth_top_classifyPoly_fu_383_ap_idle ),
    .ap_ready( grp_synth_top_classifyPoly_fu_383_ap_ready ),
    .example_0_id_address0( grp_synth_top_classifyPoly_fu_383_example_0_id_address0 ),
    .example_0_id_ce0( grp_synth_top_classifyPoly_fu_383_example_0_id_ce0 ),
    .example_0_id_q0( grp_synth_top_classifyPoly_fu_383_example_0_id_q0 ),
    .example_1_id_address0( grp_synth_top_classifyPoly_fu_383_example_1_id_address0 ),
    .example_1_id_ce0( grp_synth_top_classifyPoly_fu_383_example_1_id_ce0 ),
    .example_1_id_q0( grp_synth_top_classifyPoly_fu_383_example_1_id_q0 ),
    .example_2_id_address0( grp_synth_top_classifyPoly_fu_383_example_2_id_address0 ),
    .example_2_id_ce0( grp_synth_top_classifyPoly_fu_383_example_2_id_ce0 ),
    .example_2_id_q0( grp_synth_top_classifyPoly_fu_383_example_2_id_q0 ),
    .example_3_id_address0( grp_synth_top_classifyPoly_fu_383_example_3_id_address0 ),
    .example_3_id_ce0( grp_synth_top_classifyPoly_fu_383_example_3_id_ce0 ),
    .example_3_id_q0( grp_synth_top_classifyPoly_fu_383_example_3_id_q0 ),
    .example_0_value_address0( grp_synth_top_classifyPoly_fu_383_example_0_value_address0 ),
    .example_0_value_ce0( grp_synth_top_classifyPoly_fu_383_example_0_value_ce0 ),
    .example_0_value_q0( grp_synth_top_classifyPoly_fu_383_example_0_value_q0 ),
    .example_1_value_address0( grp_synth_top_classifyPoly_fu_383_example_1_value_address0 ),
    .example_1_value_ce0( grp_synth_top_classifyPoly_fu_383_example_1_value_ce0 ),
    .example_1_value_q0( grp_synth_top_classifyPoly_fu_383_example_1_value_q0 ),
    .example_2_value_address0( grp_synth_top_classifyPoly_fu_383_example_2_value_address0 ),
    .example_2_value_ce0( grp_synth_top_classifyPoly_fu_383_example_2_value_ce0 ),
    .example_2_value_q0( grp_synth_top_classifyPoly_fu_383_example_2_value_q0 ),
    .example_3_value_address0( grp_synth_top_classifyPoly_fu_383_example_3_value_address0 ),
    .example_3_value_ce0( grp_synth_top_classifyPoly_fu_383_example_3_value_ce0 ),
    .example_3_value_q0( grp_synth_top_classifyPoly_fu_383_example_3_value_q0 ),
    .sv_0_id_address0( grp_synth_top_classifyPoly_fu_383_sv_0_id_address0 ),
    .sv_0_id_ce0( grp_synth_top_classifyPoly_fu_383_sv_0_id_ce0 ),
    .sv_0_id_q0( grp_synth_top_classifyPoly_fu_383_sv_0_id_q0 ),
    .sv_1_id_address0( grp_synth_top_classifyPoly_fu_383_sv_1_id_address0 ),
    .sv_1_id_ce0( grp_synth_top_classifyPoly_fu_383_sv_1_id_ce0 ),
    .sv_1_id_q0( grp_synth_top_classifyPoly_fu_383_sv_1_id_q0 ),
    .sv_2_id_address0( grp_synth_top_classifyPoly_fu_383_sv_2_id_address0 ),
    .sv_2_id_ce0( grp_synth_top_classifyPoly_fu_383_sv_2_id_ce0 ),
    .sv_2_id_q0( grp_synth_top_classifyPoly_fu_383_sv_2_id_q0 ),
    .sv_3_id_address0( grp_synth_top_classifyPoly_fu_383_sv_3_id_address0 ),
    .sv_3_id_ce0( grp_synth_top_classifyPoly_fu_383_sv_3_id_ce0 ),
    .sv_3_id_q0( grp_synth_top_classifyPoly_fu_383_sv_3_id_q0 ),
    .sv_0_value_address0( grp_synth_top_classifyPoly_fu_383_sv_0_value_address0 ),
    .sv_0_value_ce0( grp_synth_top_classifyPoly_fu_383_sv_0_value_ce0 ),
    .sv_0_value_q0( grp_synth_top_classifyPoly_fu_383_sv_0_value_q0 ),
    .sv_1_value_address0( grp_synth_top_classifyPoly_fu_383_sv_1_value_address0 ),
    .sv_1_value_ce0( grp_synth_top_classifyPoly_fu_383_sv_1_value_ce0 ),
    .sv_1_value_q0( grp_synth_top_classifyPoly_fu_383_sv_1_value_q0 ),
    .sv_2_value_address0( grp_synth_top_classifyPoly_fu_383_sv_2_value_address0 ),
    .sv_2_value_ce0( grp_synth_top_classifyPoly_fu_383_sv_2_value_ce0 ),
    .sv_2_value_q0( grp_synth_top_classifyPoly_fu_383_sv_2_value_q0 ),
    .sv_3_value_address0( grp_synth_top_classifyPoly_fu_383_sv_3_value_address0 ),
    .sv_3_value_ce0( grp_synth_top_classifyPoly_fu_383_sv_3_value_ce0 ),
    .sv_3_value_q0( grp_synth_top_classifyPoly_fu_383_sv_3_value_q0 ),
    .lambda_address0( grp_synth_top_classifyPoly_fu_383_lambda_address0 ),
    .lambda_ce0( grp_synth_top_classifyPoly_fu_383_lambda_ce0 ),
    .lambda_q0( grp_synth_top_classifyPoly_fu_383_lambda_q0 ),
    .svNonZeroFeature_address0( grp_synth_top_classifyPoly_fu_383_svNonZeroFeature_address0 ),
    .svNonZeroFeature_ce0( grp_synth_top_classifyPoly_fu_383_svNonZeroFeature_ce0 ),
    .svNonZeroFeature_q0( grp_synth_top_classifyPoly_fu_383_svNonZeroFeature_q0 ),
    .nonZeroFeature_address0( grp_synth_top_classifyPoly_fu_383_nonZeroFeature_address0 ),
    .nonZeroFeature_ce0( grp_synth_top_classifyPoly_fu_383_nonZeroFeature_ce0 ),
    .nonZeroFeature_q0( grp_synth_top_classifyPoly_fu_383_nonZeroFeature_q0 ),
    .output_r_address0( grp_synth_top_classifyPoly_fu_383_output_r_address0 ),
    .output_r_ce0( grp_synth_top_classifyPoly_fu_383_output_r_ce0 ),
    .output_r_we0( grp_synth_top_classifyPoly_fu_383_output_r_we0 ),
    .output_r_d0( grp_synth_top_classifyPoly_fu_383_output_r_d0 ),
    .output_r_q0( grp_synth_top_classifyPoly_fu_383_output_r_q0 )
);

synth_top_fptrunc_64ns_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
synth_top_fptrunc_64ns_32_1_U28(
    .din0( temp_fu_427_p0 ),
    .dout( temp_fu_427_p1 )
);

synth_top_fpext_32ns_64_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
synth_top_fpext_32ns_64_1_U29(
    .din0( tmp_4_i_fu_431_p0 ),
    .dout( tmp_4_i_fu_431_p1 )
);

synth_top_dadd_64ns_64ns_64_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
synth_top_dadd_64ns_64ns_64_5_full_dsp_U30(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_435_p0 ),
    .din1( grp_fu_435_p1 ),
    .ce( grp_fu_435_ce ),
    .dout( grp_fu_435_p2 )
);

synth_top_dmul_64ns_64ns_64_6_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
synth_top_dmul_64ns_64ns_64_6_max_dsp_U31(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_440_p0 ),
    .din1( grp_fu_440_p1 ),
    .ce( grp_fu_440_ce ),
    .dout( grp_fu_440_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~((tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0) & (ap_const_logic_0 == grp_synth_top_classifyPoly_fu_383_ap_done)) & ((tmp_reg_673 == ap_const_lv1_0) | ~(ap_const_lv1_0 == exitcond_i_fu_456_p2)))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// grp_synth_top_classifyPoly_fu_383_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_synth_top_classifyPoly_fu_383_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_synth_top_classifyPoly_fu_383_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_159 & (tmp_fu_444_p2 == ap_const_lv1_0) & ~(tmp_1_fu_450_p2 == ap_const_lv1_0))) begin
            grp_synth_top_classifyPoly_fu_383_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_synth_top_classifyPoly_fu_383_ap_ready)) begin
            grp_synth_top_classifyPoly_fu_383_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == tmp_i1_fu_467_p2))) begin
        dot_i_reg_358 <= ap_const_lv64_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        dot_i_reg_358 <= dot_1_fu_667_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == tmp_i1_fu_467_p2))) begin
        p1_i_reg_334 <= ap_const_lv32_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        p1_i_reg_334 <= p1_2_reg_789;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == tmp_i1_fu_467_p2))) begin
        p2_i_reg_346 <= ap_const_lv32_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        p2_i_reg_346 <= p2_2_reg_794;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == tmp_i1_reg_699) & (ap_const_lv1_0 == tmp_i_44_fu_498_p2))) begin
        p_0_i_reg_370 <= dot_i_reg_358;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == tmp_i1_fu_467_p2))) begin
        p_0_i_reg_370 <= ap_const_lv64_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_159 & ~(tmp_fu_444_p2 == ap_const_lv1_0))) begin
        yindex_assign_reg_322 <= ap_const_lv6_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        yindex_assign_reg_322 <= i_reg_758;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        a2_reg_763 <= a2_fu_576_p3;
        y_value_load_phi_i_reg_774 <= y_value_load_phi_i_fu_605_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == tmp_27_i_reg_779) & (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16))) begin
        dot_reg_804 <= grp_fu_435_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ((ap_const_lv1_0 == tmp_i_44_fu_498_p2) | ~(ap_const_lv1_0 == tmp_i1_reg_699)))) begin
        i_reg_758 <= i_fu_539_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        nonZeroFeature_load_reg_694 <= nonZeroFeature_q0;
        tmp_i1_reg_699 <= tmp_i1_fu_467_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        p1_2_reg_789 <= p1_2_fu_651_p3;
        p2_2_reg_794 <= p2_2_fu_659_p3;
        tmp_27_i_reg_779 <= tmp_27_i_fu_613_p2;
        weight_load_reg_784 <= weight_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18)) begin
        temp_reg_814 <= temp_fu_427_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_159 & (tmp_fu_444_p2 == ap_const_lv1_0))) begin
        tmp_1_reg_677 <= tmp_1_fu_450_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == tmp_i1_fu_467_p2))) begin
        tmp_24_i_cast3_reg_703[12 : 1] <= tmp_24_i_cast3_fu_483_p1[12 : 1];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) & ~(ap_const_lv1_0 == tmp_27_i_reg_779))) begin
        tmp_30_i_reg_799 <= grp_fu_440_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == tmp_i1_reg_699) & ~(ap_const_lv1_0 == tmp_i_44_fu_498_p2))) begin
        tmp_4_reg_711 <= tmp_4_fu_513_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~((tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0) & (ap_const_logic_0 == grp_synth_top_classifyPoly_fu_383_ap_done)) & ~(tmp_reg_673 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond_i_fu_456_p2))) begin
        tmp_i_reg_684[5 : 0] <= tmp_i_fu_462_p1[5 : 0];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_159)) begin
        tmp_reg_673 <= tmp_fu_444_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_ap_done or exitcond_i_fu_456_p2)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~((tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0) & (ap_const_logic_0 == grp_synth_top_classifyPoly_fu_383_ap_done)) & ((tmp_reg_673 == ap_const_lv1_0) | ~(ap_const_lv1_0 == exitcond_i_fu_456_p2))))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_ap_done or exitcond_i_fu_456_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~((tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0) & (ap_const_logic_0 == grp_synth_top_classifyPoly_fu_383_ap_done)) & ((tmp_reg_673 == ap_const_lv1_0) | ~(ap_const_lv1_0 == exitcond_i_fu_456_p2)))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_11 assign process. ///
always @ (ap_sig_bdd_276)
begin
    if (ap_sig_bdd_276) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st13_fsm_12 assign process. ///
always @ (ap_sig_bdd_424)
begin
    if (ap_sig_bdd_424) begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st17_fsm_16 assign process. ///
always @ (ap_sig_bdd_288)
begin
    if (ap_sig_bdd_288) begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st18_fsm_17 assign process. ///
always @ (ap_sig_bdd_298)
begin
    if (ap_sig_bdd_298) begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st19_fsm_18 assign process. ///
always @ (ap_sig_bdd_307)
begin
    if (ap_sig_bdd_307) begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_39)
begin
    if (ap_sig_bdd_39) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st20_fsm_19 assign process. ///
always @ (ap_sig_bdd_383)
begin
    if (ap_sig_bdd_383) begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_174)
begin
    if (ap_sig_bdd_174) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_198)
begin
    if (ap_sig_bdd_198) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_213)
begin
    if (ap_sig_bdd_213) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st5_fsm_4 assign process. ///
always @ (ap_sig_bdd_249)
begin
    if (ap_sig_bdd_249) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st6_fsm_5 assign process. ///
always @ (ap_sig_bdd_262)
begin
    if (ap_sig_bdd_262) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_6 assign process. ///
always @ (ap_sig_bdd_433)
begin
    if (ap_sig_bdd_433) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

/// example_0_id_address0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_0_id_address0 or tmp_2_fu_527_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_0_id_address0 = tmp_2_fu_527_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_0_id_address0 = grp_synth_top_classifyPoly_fu_383_example_0_id_address0;
    end else begin
        example_0_id_address0 = 'bx;
    end
end

/// example_0_id_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_0_id_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_0_id_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_0_id_ce0 = grp_synth_top_classifyPoly_fu_383_example_0_id_ce0;
    end else begin
        example_0_id_ce0 = ap_const_logic_0;
    end
end

/// example_0_value_address0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_0_value_address0 or tmp_2_fu_527_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_0_value_address0 = tmp_2_fu_527_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_0_value_address0 = grp_synth_top_classifyPoly_fu_383_example_0_value_address0;
    end else begin
        example_0_value_address0 = 'bx;
    end
end

/// example_0_value_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_0_value_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_0_value_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_0_value_ce0 = grp_synth_top_classifyPoly_fu_383_example_0_value_ce0;
    end else begin
        example_0_value_ce0 = ap_const_logic_0;
    end
end

/// example_1_id_address0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_1_id_address0 or tmp_2_fu_527_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_1_id_address0 = tmp_2_fu_527_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_1_id_address0 = grp_synth_top_classifyPoly_fu_383_example_1_id_address0;
    end else begin
        example_1_id_address0 = 'bx;
    end
end

/// example_1_id_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_1_id_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_1_id_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_1_id_ce0 = grp_synth_top_classifyPoly_fu_383_example_1_id_ce0;
    end else begin
        example_1_id_ce0 = ap_const_logic_0;
    end
end

/// example_1_value_address0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_1_value_address0 or tmp_2_fu_527_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_1_value_address0 = tmp_2_fu_527_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_1_value_address0 = grp_synth_top_classifyPoly_fu_383_example_1_value_address0;
    end else begin
        example_1_value_address0 = 'bx;
    end
end

/// example_1_value_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_1_value_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_1_value_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_1_value_ce0 = grp_synth_top_classifyPoly_fu_383_example_1_value_ce0;
    end else begin
        example_1_value_ce0 = ap_const_logic_0;
    end
end

/// example_2_id_address0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_2_id_address0 or tmp_2_fu_527_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_2_id_address0 = tmp_2_fu_527_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_2_id_address0 = grp_synth_top_classifyPoly_fu_383_example_2_id_address0;
    end else begin
        example_2_id_address0 = 'bx;
    end
end

/// example_2_id_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_2_id_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_2_id_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_2_id_ce0 = grp_synth_top_classifyPoly_fu_383_example_2_id_ce0;
    end else begin
        example_2_id_ce0 = ap_const_logic_0;
    end
end

/// example_2_value_address0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_2_value_address0 or tmp_2_fu_527_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_2_value_address0 = tmp_2_fu_527_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_2_value_address0 = grp_synth_top_classifyPoly_fu_383_example_2_value_address0;
    end else begin
        example_2_value_address0 = 'bx;
    end
end

/// example_2_value_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_2_value_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_2_value_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_2_value_ce0 = grp_synth_top_classifyPoly_fu_383_example_2_value_ce0;
    end else begin
        example_2_value_ce0 = ap_const_logic_0;
    end
end

/// example_3_id_address0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_3_id_address0 or tmp_2_fu_527_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_3_id_address0 = tmp_2_fu_527_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_3_id_address0 = grp_synth_top_classifyPoly_fu_383_example_3_id_address0;
    end else begin
        example_3_id_address0 = 'bx;
    end
end

/// example_3_id_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_3_id_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_3_id_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_3_id_ce0 = grp_synth_top_classifyPoly_fu_383_example_3_id_ce0;
    end else begin
        example_3_id_ce0 = ap_const_logic_0;
    end
end

/// example_3_value_address0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_3_value_address0 or tmp_2_fu_527_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_3_value_address0 = tmp_2_fu_527_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_3_value_address0 = grp_synth_top_classifyPoly_fu_383_example_3_value_address0;
    end else begin
        example_3_value_address0 = 'bx;
    end
end

/// example_3_value_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or grp_synth_top_classifyPoly_fu_383_example_3_value_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        example_3_value_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        example_3_value_ce0 = grp_synth_top_classifyPoly_fu_383_example_3_value_ce0;
    end else begin
        example_3_value_ce0 = ap_const_logic_0;
    end
end

/// lambda_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_lambda_ce0)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        lambda_ce0 = grp_synth_top_classifyPoly_fu_383_lambda_ce0;
    end else begin
        lambda_ce0 = ap_const_logic_0;
    end
end

/// nonZeroFeature_address0 assign process. ///
always @ (tmp_i_fu_462_p1 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_nonZeroFeature_address0 or ap_sig_bdd_180)
begin
    nonZeroFeature_address0 = tmp_i_fu_462_p1;
end

/// nonZeroFeature_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_ap_done or grp_synth_top_classifyPoly_fu_383_nonZeroFeature_ce0 or ap_sig_bdd_180)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        if (~((tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0) & (ap_const_logic_0 == grp_synth_top_classifyPoly_fu_383_ap_done))) begin
            nonZeroFeature_ce0 = ap_const_logic_1;
        end else if (ap_sig_bdd_180) begin
            nonZeroFeature_ce0 = grp_synth_top_classifyPoly_fu_383_nonZeroFeature_ce0;
        end else begin
            nonZeroFeature_ce0 = ap_const_logic_0;
        end
    end else begin
        nonZeroFeature_ce0 = ap_const_logic_0;
    end
end

/// output_r_address0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or tmp_i_reg_684 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_output_r_address0 or ap_sig_cseq_ST_st20_fsm_19)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        output_r_address0 = tmp_i_reg_684;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        output_r_address0 = grp_synth_top_classifyPoly_fu_383_output_r_address0;
    end else begin
        output_r_address0 = 'bx;
    end
end

/// output_r_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_output_r_ce0 or ap_sig_cseq_ST_st20_fsm_19)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        output_r_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        output_r_ce0 = grp_synth_top_classifyPoly_fu_383_output_r_ce0;
    end else begin
        output_r_ce0 = ap_const_logic_0;
    end
end

/// output_r_d0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_output_r_d0 or ap_sig_cseq_ST_st20_fsm_19 or tmp_4_i_fu_431_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        output_r_d0 = tmp_4_i_fu_431_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        output_r_d0 = grp_synth_top_classifyPoly_fu_383_output_r_d0;
    end else begin
        output_r_d0 = 'bx;
    end
end

/// output_r_we0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_output_r_we0 or ap_sig_cseq_ST_st20_fsm_19)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        output_r_we0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        output_r_we0 = grp_synth_top_classifyPoly_fu_383_output_r_we0;
    end else begin
        output_r_we0 = ap_const_logic_0;
    end
end

/// svNonZeroFeature_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_svNonZeroFeature_ce0)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        svNonZeroFeature_ce0 = grp_synth_top_classifyPoly_fu_383_svNonZeroFeature_ce0;
    end else begin
        svNonZeroFeature_ce0 = ap_const_logic_0;
    end
end

/// sv_0_id_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_sv_0_id_ce0)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        sv_0_id_ce0 = grp_synth_top_classifyPoly_fu_383_sv_0_id_ce0;
    end else begin
        sv_0_id_ce0 = ap_const_logic_0;
    end
end

/// sv_0_value_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_sv_0_value_ce0)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        sv_0_value_ce0 = grp_synth_top_classifyPoly_fu_383_sv_0_value_ce0;
    end else begin
        sv_0_value_ce0 = ap_const_logic_0;
    end
end

/// sv_1_id_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_sv_1_id_ce0)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        sv_1_id_ce0 = grp_synth_top_classifyPoly_fu_383_sv_1_id_ce0;
    end else begin
        sv_1_id_ce0 = ap_const_logic_0;
    end
end

/// sv_1_value_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_sv_1_value_ce0)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        sv_1_value_ce0 = grp_synth_top_classifyPoly_fu_383_sv_1_value_ce0;
    end else begin
        sv_1_value_ce0 = ap_const_logic_0;
    end
end

/// sv_2_id_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_sv_2_id_ce0)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        sv_2_id_ce0 = grp_synth_top_classifyPoly_fu_383_sv_2_id_ce0;
    end else begin
        sv_2_id_ce0 = ap_const_logic_0;
    end
end

/// sv_2_value_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_sv_2_value_ce0)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        sv_2_value_ce0 = grp_synth_top_classifyPoly_fu_383_sv_2_value_ce0;
    end else begin
        sv_2_value_ce0 = ap_const_logic_0;
    end
end

/// sv_3_id_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_sv_3_id_ce0)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        sv_3_id_ce0 = grp_synth_top_classifyPoly_fu_383_sv_3_id_ce0;
    end else begin
        sv_3_id_ce0 = ap_const_logic_0;
    end
end

/// sv_3_value_ce0 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677 or ap_sig_cseq_ST_st2_fsm_1 or grp_synth_top_classifyPoly_fu_383_sv_3_value_ce0)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0))) begin
        sv_3_value_ce0 = grp_synth_top_classifyPoly_fu_383_sv_3_value_ce0;
    end else begin
        sv_3_value_ce0 = ap_const_logic_0;
    end
end

/// weight_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st5_fsm_4)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        weight_ce0 = ap_const_logic_1;
    end else begin
        weight_ce0 = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or tmp_reg_673 or ap_sig_bdd_159 or tmp_1_reg_677 or grp_synth_top_classifyPoly_fu_383_ap_done or exitcond_i_fu_456_p2 or tmp_i1_reg_699 or tmp_i_44_fu_498_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_159) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((~((tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0) & (ap_const_logic_0 == grp_synth_top_classifyPoly_fu_383_ap_done)) & ((tmp_reg_673 == ap_const_lv1_0) | ~(ap_const_lv1_0 == exitcond_i_fu_456_p2)))) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else if ((~((tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0) & (ap_const_logic_0 == grp_synth_top_classifyPoly_fu_383_ap_done)) & ~(tmp_reg_673 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond_i_fu_456_p2))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (((ap_const_lv1_0 == tmp_i_44_fu_498_p2) | ~(ap_const_lv1_0 == tmp_i1_reg_699))) begin
                ap_NS_fsm = ap_ST_st19_fsm_18;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : 
        begin
            ap_NS_fsm = ap_ST_st15_fsm_14;
        end
        ap_ST_st15_fsm_14 : 
        begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : 
        begin
            ap_NS_fsm = ap_ST_st17_fsm_16;
        end
        ap_ST_st17_fsm_16 : 
        begin
            ap_NS_fsm = ap_ST_st18_fsm_17;
        end
        ap_ST_st18_fsm_17 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st19_fsm_18 : 
        begin
            ap_NS_fsm = ap_ST_st20_fsm_19;
        end
        ap_ST_st20_fsm_19 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a2_fu_576_p3 = ((sel_tmp4_i_fu_571_p2[0:0]===1'b1)? example_2_id_q0: sel_tmp3_i_fu_563_p3);

/// ap_sig_bdd_159 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_159 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_174 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_174 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_180 assign process. ///
always @ (tmp_reg_673 or tmp_1_reg_677)
begin
    ap_sig_bdd_180 = ((tmp_reg_673 == ap_const_lv1_0) & ~(tmp_1_reg_677 == ap_const_lv1_0));
end

/// ap_sig_bdd_198 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_198 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_213 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_213 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_249 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_249 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_262 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_262 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_276 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_276 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end

/// ap_sig_bdd_288 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_288 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_10]);
end

/// ap_sig_bdd_298 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_298 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end

/// ap_sig_bdd_307 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_307 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_12]);
end

/// ap_sig_bdd_383 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_383 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_13]);
end

/// ap_sig_bdd_39 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_39 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_424 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_424 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end

/// ap_sig_bdd_433 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_433 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end
assign dot_1_fu_667_p3 = ((tmp_27_i_reg_779[0:0]===1'b1)? dot_reg_804: dot_i_reg_358);
assign exitcond_i_fu_456_p2 = (yindex_assign_reg_322 == ap_const_lv6_33? 1'b1: 1'b0);
assign grp_fu_435_ce = ap_const_logic_1;
assign grp_fu_435_p0 = dot_i_reg_358;
assign grp_fu_435_p1 = tmp_30_i_reg_799;
assign grp_fu_440_ce = ap_const_logic_1;
assign grp_fu_440_p0 = weight_load_reg_784;
assign grp_fu_440_p1 = y_value_load_phi_i_reg_774;
assign grp_synth_top_classifyPoly_fu_383_ap_start = grp_synth_top_classifyPoly_fu_383_ap_start_ap_start_reg;
assign grp_synth_top_classifyPoly_fu_383_example_0_id_q0 = example_0_id_q0;
assign grp_synth_top_classifyPoly_fu_383_example_0_value_q0 = example_0_value_q0;
assign grp_synth_top_classifyPoly_fu_383_example_1_id_q0 = example_1_id_q0;
assign grp_synth_top_classifyPoly_fu_383_example_1_value_q0 = example_1_value_q0;
assign grp_synth_top_classifyPoly_fu_383_example_2_id_q0 = example_2_id_q0;
assign grp_synth_top_classifyPoly_fu_383_example_2_value_q0 = example_2_value_q0;
assign grp_synth_top_classifyPoly_fu_383_example_3_id_q0 = example_3_id_q0;
assign grp_synth_top_classifyPoly_fu_383_example_3_value_q0 = example_3_value_q0;
assign grp_synth_top_classifyPoly_fu_383_lambda_q0 = lambda_q0;
assign grp_synth_top_classifyPoly_fu_383_nonZeroFeature_q0 = nonZeroFeature_q0;
assign grp_synth_top_classifyPoly_fu_383_output_r_q0 = output_r_q0;
assign grp_synth_top_classifyPoly_fu_383_svNonZeroFeature_q0 = svNonZeroFeature_q0;
assign grp_synth_top_classifyPoly_fu_383_sv_0_id_q0 = sv_0_id_q0;
assign grp_synth_top_classifyPoly_fu_383_sv_0_value_q0 = sv_0_value_q0;
assign grp_synth_top_classifyPoly_fu_383_sv_1_id_q0 = sv_1_id_q0;
assign grp_synth_top_classifyPoly_fu_383_sv_1_value_q0 = sv_1_value_q0;
assign grp_synth_top_classifyPoly_fu_383_sv_2_id_q0 = sv_2_id_q0;
assign grp_synth_top_classifyPoly_fu_383_sv_2_value_q0 = sv_2_value_q0;
assign grp_synth_top_classifyPoly_fu_383_sv_3_id_q0 = sv_3_id_q0;
assign grp_synth_top_classifyPoly_fu_383_sv_3_value_q0 = sv_3_value_q0;
assign i_fu_539_p2 = (yindex_assign_reg_322 + ap_const_lv6_1);
assign lambda_address0 = grp_synth_top_classifyPoly_fu_383_lambda_address0;
assign not_i_fu_492_p2 = ($signed(p1_i_reg_334) < $signed(32'b110011)? 1'b1: 1'b0);
assign p1_1_fu_635_p3 = ((tmp_29_i2_fu_618_p2[0:0]===1'b1)? p1_i_reg_334: p1_fu_629_p2);
assign p1_2_fu_651_p3 = ((tmp_27_i_fu_613_p2[0:0]===1'b1)? p1_fu_629_p2: p1_1_fu_635_p3);
assign p1_fu_629_p2 = (ap_const_lv32_1 + p1_i_reg_334);
assign p2_1_fu_643_p3 = ((tmp_29_i2_fu_618_p2[0:0]===1'b1)? p2_fu_623_p2: p2_i_reg_346);
assign p2_2_fu_659_p3 = ((tmp_27_i_fu_613_p2[0:0]===1'b1)? p2_fu_623_p2: p2_1_fu_643_p3);
assign p2_fu_623_p2 = (ap_const_lv32_1 + p2_i_reg_346);
assign sel_tmp1_i_fu_550_p3 = ((sel_tmp_i_fu_545_p2[0:0]===1'b1)? example_0_id_q0: example_3_id_q0);
assign sel_tmp2_i_fu_558_p2 = (tmp_4_reg_711 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp3_i_fu_563_p3 = ((sel_tmp2_i_fu_558_p2[0:0]===1'b1)? example_1_id_q0: sel_tmp1_i_fu_550_p3);
assign sel_tmp4_i_fu_571_p2 = (tmp_4_reg_711 == ap_const_lv2_2? 1'b1: 1'b0);
assign sel_tmp7_i_fu_589_p3 = ((sel_tmp_i_fu_545_p2[0:0]===1'b1)? example_0_value_q0: example_3_value_q0);
assign sel_tmp9_i_fu_597_p3 = ((sel_tmp2_i_fu_558_p2[0:0]===1'b1)? example_1_value_q0: sel_tmp7_i_fu_589_p3);
assign sel_tmp_i_fu_545_p2 = (tmp_4_reg_711 == ap_const_lv2_0? 1'b1: 1'b0);
assign sum_i_fu_508_p2 = ($signed(tmp_24_i_cast3_reg_703) + $signed(tmp_27_cast_i_cast_fu_504_p1));
assign svNonZeroFeature_address0 = grp_synth_top_classifyPoly_fu_383_svNonZeroFeature_address0;
assign sv_0_id_address0 = grp_synth_top_classifyPoly_fu_383_sv_0_id_address0;
assign sv_0_value_address0 = grp_synth_top_classifyPoly_fu_383_sv_0_value_address0;
assign sv_1_id_address0 = grp_synth_top_classifyPoly_fu_383_sv_1_id_address0;
assign sv_1_value_address0 = grp_synth_top_classifyPoly_fu_383_sv_1_value_address0;
assign sv_2_id_address0 = grp_synth_top_classifyPoly_fu_383_sv_2_id_address0;
assign sv_2_value_address0 = grp_synth_top_classifyPoly_fu_383_sv_2_value_address0;
assign sv_3_id_address0 = grp_synth_top_classifyPoly_fu_383_sv_3_id_address0;
assign sv_3_value_address0 = grp_synth_top_classifyPoly_fu_383_sv_3_value_address0;
assign temp_fu_427_p0 = p_0_i_reg_370;
assign tmp_1_fu_450_p2 = (kernelType == ap_const_lv32_1? 1'b1: 1'b0);
assign tmp_24_i_cast3_fu_483_p1 = tmp_24_i_fu_477_p2;
assign tmp_24_i_fu_477_p0 = tmp_24_i_fu_477_p00;
assign tmp_24_i_fu_477_p00 = yindex_assign_reg_322;
assign tmp_24_i_fu_477_p2 = (tmp_24_i_fu_477_p0 * $signed('h32));
assign tmp_25_i_fu_487_p2 = ($signed(p2_i_reg_346) < $signed(nonZeroFeature_load_reg_694)? 1'b1: 1'b0);
assign tmp_27_cast_i_cast_fu_504_p1 = $signed(p2_i_reg_346);
assign tmp_27_i_fu_613_p2 = (p1_i_reg_334 == a2_reg_763? 1'b1: 1'b0);
assign tmp_28_i_fu_584_p1 = $signed(p1_i_reg_334);
assign tmp_29_i2_fu_618_p2 = ($signed(p1_i_reg_334) > $signed(a2_reg_763)? 1'b1: 1'b0);
assign tmp_2_fu_527_p1 = $signed(tmp_3_fu_517_p4);
assign tmp_3_fu_517_p4 = {{sum_i_fu_508_p2[ap_const_lv32_6 : ap_const_lv32_2]}};
assign tmp_4_fu_513_p1 = sum_i_fu_508_p2[1:0];
assign tmp_4_i_fu_431_p0 = temp_reg_814;
assign tmp_fu_444_p2 = (kernelType == ap_const_lv32_0? 1'b1: 1'b0);
assign tmp_i1_fu_467_p2 = (nonZeroFeature_q0 == ap_const_lv32_0? 1'b1: 1'b0);
assign tmp_i_44_fu_498_p2 = (tmp_25_i_fu_487_p2 & not_i_fu_492_p2);
assign tmp_i_fu_462_p1 = yindex_assign_reg_322;
assign weight_address0 = tmp_28_i_fu_584_p1;
assign y_value_load_phi_i_fu_605_p3 = ((sel_tmp4_i_fu_571_p2[0:0]===1'b1)? example_2_value_q0: sel_tmp9_i_fu_597_p3);
always @ (posedge ap_clk)
begin
    tmp_i_reg_684[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    tmp_24_i_cast3_reg_703[0] <= 1'b0;
    tmp_24_i_cast3_reg_703[32:13] <= 20'b00000000000000000000;
end



endmodule //synth_top_writeResult

