lappend pragmaStatus0 {pragma "DATAFLOW" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "ARRAY_PARTITION" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "example"}
lappend pragmaStatus2 {pragma "ARRAY_PARTITION" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "sv"}
lappend pragmaStatus3 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "wtDotProduct/wtDotProduct_while" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_TRIPCOUNT' cannot be applied: Function 'wtDotProduct' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "classifyLinear/LINEAR_FOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_TRIPCOUNT' cannot be applied: Function 'classifyLinear' does not exist in any synthesis source file."}
lappend pragmaStatus5 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "classifyPoly/POLY_INIT_FOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_TRIPCOUNT' cannot be applied: Function 'classifyPoly' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "classifyPoly/POLY_OUTER_FOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_TRIPCOUNT' cannot be applied: Function 'classifyPoly' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "classifyPoly/POLY_INNER_FOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_TRIPCOUNT' cannot be applied: Function 'classifyPoly' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "dotProduct/dotProduct_while" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'LOOP_TRIPCOUNT' cannot be applied: Function 'dotProduct' does not exist in any synthesis source file."}
lappend pragmaStatus9 {pragma "INLINE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "dotProduct" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'dotProduct' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "PIPELINE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "classifyPoly/POLY_INIT_FOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'classifyPoly' does not exist in any synthesis source file."}
lappend pragmaStatus11 {pragma "PIPELINE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "classifyPoly/POLY_INNER_FOR_LOOP" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'classifyPoly' does not exist in any synthesis source file."}
lappend pragmaStatus12 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus14 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus15 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus16 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus17 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus18 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus19 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus20 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/initialize.c" location "synth_top" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus0 {pragma "DATAFLOW" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'synth_top' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "ARRAY_PARTITION" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'synth_top' does not exist in any synthesis source file." variable "example"}
lappend pragmaStatus2 {pragma "ARRAY_PARTITION" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'synth_top' does not exist in any synthesis source file." variable "sv"}
lappend pragmaStatus3 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "wtDotProduct/wtDotProduct_while" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "classifyLinear/LINEAR_FOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "classifyPoly/POLY_INIT_FOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "classifyPoly/POLY_OUTER_FOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "classifyPoly/POLY_INNER_FOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "LOOP_TRIPCOUNT" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "dotProduct/dotProduct_while" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "INLINE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "dotProduct" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "PIPELINE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "classifyPoly/POLY_INIT_FOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "PIPELINE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "classifyPoly/POLY_INNER_FOR_LOOP" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'synth_top' does not exist in any synthesis source file."}
lappend pragmaStatus13 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'synth_top' does not exist in any synthesis source file."}
lappend pragmaStatus14 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'synth_top' does not exist in any synthesis source file."}
lappend pragmaStatus15 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'synth_top' does not exist in any synthesis source file."}
lappend pragmaStatus16 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'synth_top' does not exist in any synthesis source file."}
lappend pragmaStatus17 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'synth_top' does not exist in any synthesis source file."}
lappend pragmaStatus18 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'synth_top' does not exist in any synthesis source file."}
lappend pragmaStatus19 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'synth_top' does not exist in any synthesis source file."}
lappend pragmaStatus20 {pragma "INTERFACE" source "C:/Users/Owner/Desktop/SVM/SMO/smosynth/smosynth/classify.c" location "synth_top" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'synth_top' does not exist in any synthesis source file."}
