# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2015.1
# Copyright (C) 2015 Xilinx Inc. All rights reserved.
# 
# ==============================================================

proc sc_sim_check { ret err logfile } {
    set errfile "err.log"
    if {[file exists $errfile] && [file size $errfile] != 0} {
        set fl [open $errfile r]
        while {[gets $fl line] >= 0} {
            if {[string first "AESL_mErrNo = " $line] == 0} {
                set mismatch_num [string range $line [string length "AESL_mErrNo = "] end]
                if {$mismatch_num != 0} {
                    puts "@E SystemC simulation FAILED with ${mismatch_num} mismatches detected."
                    break
                }
            }
        }
    }
    if {$ret || $err != ""} {
        if { [lindex $::errorCode 0] eq "CHILDSTATUS"} {
            set status [lindex $::errorCode 2]
            if {$status != ""} {
                puts "@E Simulation failed: Function \'main\' returns nonzero value \'$status\'."
            } else {
                puts "@E Simulation failed."
            }
        } else {
            puts "@E Simulation failed."
        }
    }
    if {[file exists $logfile]} {
        set cmdret [catch {eval exec "grep \"Error:\" $logfile"} err]
        file delete -force $logfile
        if {$cmdret == 0} {
            puts "@E Simulation failed."
        }
    }
}

proc rtl_sim_check { } {
    set errfile "err.log"
    if {[file exists $errfile] && [file size $errfile] != 0} {
        set fl [open $errfile r]
        set unmatch_num 0
        while {[gets $fl line] >= 0} {
            if {[string first "unmatched" $line] != -1} {
                set unmatch_num [expr $unmatch_num + 1]
            }
        }
        if {$unmatch_num != 0} {
            puts "@E Simulation FAILED with ${unmatch_num} mismatches detected."
        }
    }
    if {[file exists ".aesl_error"]} {
        set errfl [open ".aesl_error" r]
        gets $errfl line
        if {$line != 0} {
            puts "@E Simulation failed: Function \'main\' returns nonzero value \'$line\'."
        }
    }
    if {[file exists ".exit.err"]} {
        puts "@E Simulation failed."
    }
}

proc check_tvin_file {} {
    set rtlfilelist {
         "c.synth_top.autotvin_example_0_id.dat"
         "c.synth_top.autotvin_example_1_id.dat"
         "c.synth_top.autotvin_example_2_id.dat"
         "c.synth_top.autotvin_example_3_id.dat"
         "c.synth_top.autotvin_example_0_value.dat"
         "c.synth_top.autotvin_example_1_value.dat"
         "c.synth_top.autotvin_example_2_value.dat"
         "c.synth_top.autotvin_example_3_value.dat"
         "c.synth_top.autotvin_sv_0_id.dat"
         "c.synth_top.autotvin_sv_1_id.dat"
         "c.synth_top.autotvin_sv_2_id.dat"
         "c.synth_top.autotvin_sv_3_id.dat"
         "c.synth_top.autotvin_sv_0_value.dat"
         "c.synth_top.autotvin_sv_1_value.dat"
         "c.synth_top.autotvin_sv_2_value.dat"
         "c.synth_top.autotvin_sv_3_value.dat"
         "c.synth_top.autotvin_lambda.dat"
         "c.synth_top.autotvin_svNonZeroFeature.dat"
         "c.synth_top.autotvin_nonZeroFeature.dat"
         "c.synth_top.autotvin_weight.dat"
         "c.synth_top.autotvin_output_r.dat"
         "c.synth_top.autotvin_kernelType.dat"
         "c.synth_top.autotvout_output_r.dat"
         "c.synth_top.autotvout_ap_return.dat"
    }
    foreach rtlfile $rtlfilelist {
        if {[file isfile $rtlfile]} {
        } else {
            puts "@E \[SIM-320\] C TB testing failed. Please check C TB or re-run cosim.  "
            return 1
        }
        set ret [catch {eval exec "grep /runtime $rtlfile"} err]
        if { $ret } {
            puts "@E \[SIM-320\] C TB testing failed. Please check C TB or re-run cosim.  "
            return 1
        }
    }
    return 0
}

proc check_tvout_file {} {
    set rtlfilelist {
         "rtl.synth_top.autotvout_output_r.dat"
         "rtl.synth_top.autotvout_ap_return.dat"
    }
    foreach rtlfile $rtlfilelist {
        if {[file isfile $rtlfile]} {
        } else {
            puts "@E \[SIM-303\] Aborting co-simulation: RTL simulation failed.  "
            return 1
        }
        set ret [catch {eval exec "grep /runtime $rtlfile"} err]
        if { $ret } {
            puts "@E \[SIM-303\] Aborting co-simulation: RTL simulation failed.  "
            return 1
        }
    }
    return 0
}
