webtalk_init -webtalk_dir C:\\Users\\Owner\\Desktop\\SVM\\SMO\\smosynth\\smosynth\\smo_linear\\smo_linear.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 23 18:15:53 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "mgke7ksfcamht86m72b5ohha7j" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1432401886244" -context "sdk\\\\hardware/1432401886244"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1432401886244"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1432401886244"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.1" -context "sdk\\\\hardware/1432401886244"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1432401886244"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1432401886244"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1432401886244"
webtalk_add_data -client sdk -key uid -value "1432401962690" -context "sdk\\\\bsp/1432401962690"
webtalk_add_data -client sdk -key hwid -value "1432401886244" -context "sdk\\\\bsp/1432401962690"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1432401962690"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1432401962690"
webtalk_add_data -client sdk -key uid -value "1432402086107" -context "sdk\\\\application/1432402086107"
webtalk_add_data -client sdk -key hwid -value "1432401886244" -context "sdk\\\\application/1432402086107"
webtalk_add_data -client sdk -key bspid -value "1432401962690" -context "sdk\\\\application/1432402086107"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1432402086107"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1432402086107"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1432402086107"
webtalk_transmit -clientid 1706848652 -regid "" -xml C:\\Users\\Owner\\Desktop\\SVM\\SMO\\smosynth\\smosynth\\smo_linear\\smo_linear.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Owner\\Desktop\\SVM\\SMO\\smosynth\\smosynth\\smo_linear\\smo_linear.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Owner\\Desktop\\SVM\\SMO\\smosynth\\smosynth\\smo_linear\\smo_linear.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
