// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _synth_top_writeResult_HH_
#define _synth_top_writeResult_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "synth_top_classifyPoly.h"
#include "synth_top_classifyLinear.h"

namespace ap_rtl {

struct synth_top_writeResult : public sc_module {
    // Port declarations 73
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<10> > example_0_id_address0;
    sc_out< sc_logic > example_0_id_ce0;
    sc_in< sc_lv<32> > example_0_id_q0;
    sc_out< sc_lv<10> > example_1_id_address0;
    sc_out< sc_logic > example_1_id_ce0;
    sc_in< sc_lv<32> > example_1_id_q0;
    sc_out< sc_lv<10> > example_2_id_address0;
    sc_out< sc_logic > example_2_id_ce0;
    sc_in< sc_lv<32> > example_2_id_q0;
    sc_out< sc_lv<10> > example_3_id_address0;
    sc_out< sc_logic > example_3_id_ce0;
    sc_in< sc_lv<32> > example_3_id_q0;
    sc_out< sc_lv<10> > example_0_value_address0;
    sc_out< sc_logic > example_0_value_ce0;
    sc_in< sc_lv<64> > example_0_value_q0;
    sc_out< sc_lv<10> > example_1_value_address0;
    sc_out< sc_logic > example_1_value_ce0;
    sc_in< sc_lv<64> > example_1_value_q0;
    sc_out< sc_lv<10> > example_2_value_address0;
    sc_out< sc_logic > example_2_value_ce0;
    sc_in< sc_lv<64> > example_2_value_q0;
    sc_out< sc_lv<10> > example_3_value_address0;
    sc_out< sc_logic > example_3_value_ce0;
    sc_in< sc_lv<64> > example_3_value_q0;
    sc_out< sc_lv<9> > sv_0_id_address0;
    sc_out< sc_logic > sv_0_id_ce0;
    sc_in< sc_lv<32> > sv_0_id_q0;
    sc_out< sc_lv<9> > sv_1_id_address0;
    sc_out< sc_logic > sv_1_id_ce0;
    sc_in< sc_lv<32> > sv_1_id_q0;
    sc_out< sc_lv<9> > sv_2_id_address0;
    sc_out< sc_logic > sv_2_id_ce0;
    sc_in< sc_lv<32> > sv_2_id_q0;
    sc_out< sc_lv<9> > sv_3_id_address0;
    sc_out< sc_logic > sv_3_id_ce0;
    sc_in< sc_lv<32> > sv_3_id_q0;
    sc_out< sc_lv<9> > sv_0_value_address0;
    sc_out< sc_logic > sv_0_value_ce0;
    sc_in< sc_lv<64> > sv_0_value_q0;
    sc_out< sc_lv<9> > sv_1_value_address0;
    sc_out< sc_logic > sv_1_value_ce0;
    sc_in< sc_lv<64> > sv_1_value_q0;
    sc_out< sc_lv<9> > sv_2_value_address0;
    sc_out< sc_logic > sv_2_value_ce0;
    sc_in< sc_lv<64> > sv_2_value_q0;
    sc_out< sc_lv<9> > sv_3_value_address0;
    sc_out< sc_logic > sv_3_value_ce0;
    sc_in< sc_lv<64> > sv_3_value_q0;
    sc_out< sc_lv<6> > lambda_address0;
    sc_out< sc_logic > lambda_ce0;
    sc_in< sc_lv<64> > lambda_q0;
    sc_out< sc_lv<6> > svNonZeroFeature_address0;
    sc_out< sc_logic > svNonZeroFeature_ce0;
    sc_in< sc_lv<32> > svNonZeroFeature_q0;
    sc_out< sc_lv<6> > nonZeroFeature_address0;
    sc_out< sc_logic > nonZeroFeature_ce0;
    sc_in< sc_lv<32> > nonZeroFeature_q0;
    sc_out< sc_lv<6> > weight_address0;
    sc_out< sc_logic > weight_ce0;
    sc_in< sc_lv<64> > weight_q0;
    sc_out< sc_lv<6> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<64> > output_r_d0;
    sc_in< sc_lv<64> > output_r_q0;
    sc_in< sc_lv<32> > kernelType;


    // Module declarations
    synth_top_writeResult(sc_module_name name);
    SC_HAS_PROCESS(synth_top_writeResult);

    ~synth_top_writeResult();

    sc_trace_file* mVcdFile;

    synth_top_classifyPoly* grp_synth_top_classifyPoly_fu_149;
    synth_top_classifyLinear* grp_synth_top_classifyLinear_fu_193;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_21;
    sc_signal< sc_lv<1> > tmp_fu_219_p2;
    sc_signal< sc_lv<1> > tmp_reg_231;
    sc_signal< bool > ap_sig_bdd_141;
    sc_signal< sc_lv<1> > tmp_1_fu_225_p2;
    sc_signal< sc_lv<1> > tmp_1_reg_235;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_ap_start;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_ap_done;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_ap_idle;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_ap_ready;
    sc_signal< sc_lv<10> > grp_synth_top_classifyPoly_fu_149_example_0_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_example_0_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyPoly_fu_149_example_0_id_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyPoly_fu_149_example_1_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_example_1_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyPoly_fu_149_example_1_id_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyPoly_fu_149_example_2_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_example_2_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyPoly_fu_149_example_2_id_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyPoly_fu_149_example_3_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_example_3_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyPoly_fu_149_example_3_id_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyPoly_fu_149_example_0_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_example_0_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyPoly_fu_149_example_0_value_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyPoly_fu_149_example_1_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_example_1_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyPoly_fu_149_example_1_value_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyPoly_fu_149_example_2_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_example_2_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyPoly_fu_149_example_2_value_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyPoly_fu_149_example_3_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_example_3_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyPoly_fu_149_example_3_value_q0;
    sc_signal< sc_lv<9> > grp_synth_top_classifyPoly_fu_149_sv_0_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_sv_0_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyPoly_fu_149_sv_0_id_q0;
    sc_signal< sc_lv<9> > grp_synth_top_classifyPoly_fu_149_sv_1_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_sv_1_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyPoly_fu_149_sv_1_id_q0;
    sc_signal< sc_lv<9> > grp_synth_top_classifyPoly_fu_149_sv_2_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_sv_2_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyPoly_fu_149_sv_2_id_q0;
    sc_signal< sc_lv<9> > grp_synth_top_classifyPoly_fu_149_sv_3_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_sv_3_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyPoly_fu_149_sv_3_id_q0;
    sc_signal< sc_lv<9> > grp_synth_top_classifyPoly_fu_149_sv_0_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_sv_0_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyPoly_fu_149_sv_0_value_q0;
    sc_signal< sc_lv<9> > grp_synth_top_classifyPoly_fu_149_sv_1_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_sv_1_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyPoly_fu_149_sv_1_value_q0;
    sc_signal< sc_lv<9> > grp_synth_top_classifyPoly_fu_149_sv_2_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_sv_2_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyPoly_fu_149_sv_2_value_q0;
    sc_signal< sc_lv<9> > grp_synth_top_classifyPoly_fu_149_sv_3_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_sv_3_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyPoly_fu_149_sv_3_value_q0;
    sc_signal< sc_lv<6> > grp_synth_top_classifyPoly_fu_149_lambda_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_lambda_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyPoly_fu_149_lambda_q0;
    sc_signal< sc_lv<6> > grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_q0;
    sc_signal< sc_lv<6> > grp_synth_top_classifyPoly_fu_149_nonZeroFeature_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_nonZeroFeature_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyPoly_fu_149_nonZeroFeature_q0;
    sc_signal< sc_lv<6> > grp_synth_top_classifyPoly_fu_149_output_r_address0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_output_r_ce0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_output_r_we0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyPoly_fu_149_output_r_d0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyPoly_fu_149_output_r_q0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_ap_start;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_ap_done;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_ap_idle;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_ap_ready;
    sc_signal< sc_lv<10> > grp_synth_top_classifyLinear_fu_193_example_0_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_example_0_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyLinear_fu_193_example_0_id_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyLinear_fu_193_example_1_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_example_1_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyLinear_fu_193_example_1_id_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyLinear_fu_193_example_2_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_example_2_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyLinear_fu_193_example_2_id_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyLinear_fu_193_example_3_id_address0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_example_3_id_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyLinear_fu_193_example_3_id_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyLinear_fu_193_example_0_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_example_0_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyLinear_fu_193_example_0_value_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyLinear_fu_193_example_1_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_example_1_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyLinear_fu_193_example_1_value_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyLinear_fu_193_example_2_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_example_2_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyLinear_fu_193_example_2_value_q0;
    sc_signal< sc_lv<10> > grp_synth_top_classifyLinear_fu_193_example_3_value_address0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_example_3_value_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyLinear_fu_193_example_3_value_q0;
    sc_signal< sc_lv<6> > grp_synth_top_classifyLinear_fu_193_nonZeroFeature_address0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_nonZeroFeature_ce0;
    sc_signal< sc_lv<32> > grp_synth_top_classifyLinear_fu_193_nonZeroFeature_q0;
    sc_signal< sc_lv<6> > grp_synth_top_classifyLinear_fu_193_weight_address0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_weight_ce0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyLinear_fu_193_weight_q0;
    sc_signal< sc_lv<6> > grp_synth_top_classifyLinear_fu_193_output_r_address0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_output_r_ce0;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_output_r_we0;
    sc_signal< sc_lv<64> > grp_synth_top_classifyLinear_fu_193_output_r_d0;
    sc_signal< sc_logic > grp_synth_top_classifyPoly_fu_149_ap_start_ap_start_reg;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_268;
    sc_signal< sc_logic > grp_synth_top_classifyLinear_fu_193_ap_start_ap_start_reg;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    sc_signal< bool > ap_sig_bdd_274;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_st1_fsm_0;
    static const sc_lv<2> ap_ST_st2_fsm_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_141();
    void thread_ap_sig_bdd_21();
    void thread_ap_sig_bdd_268();
    void thread_ap_sig_bdd_274();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_example_0_id_address0();
    void thread_example_0_id_ce0();
    void thread_example_0_value_address0();
    void thread_example_0_value_ce0();
    void thread_example_1_id_address0();
    void thread_example_1_id_ce0();
    void thread_example_1_value_address0();
    void thread_example_1_value_ce0();
    void thread_example_2_id_address0();
    void thread_example_2_id_ce0();
    void thread_example_2_value_address0();
    void thread_example_2_value_ce0();
    void thread_example_3_id_address0();
    void thread_example_3_id_ce0();
    void thread_example_3_value_address0();
    void thread_example_3_value_ce0();
    void thread_grp_synth_top_classifyLinear_fu_193_ap_start();
    void thread_grp_synth_top_classifyLinear_fu_193_example_0_id_q0();
    void thread_grp_synth_top_classifyLinear_fu_193_example_0_value_q0();
    void thread_grp_synth_top_classifyLinear_fu_193_example_1_id_q0();
    void thread_grp_synth_top_classifyLinear_fu_193_example_1_value_q0();
    void thread_grp_synth_top_classifyLinear_fu_193_example_2_id_q0();
    void thread_grp_synth_top_classifyLinear_fu_193_example_2_value_q0();
    void thread_grp_synth_top_classifyLinear_fu_193_example_3_id_q0();
    void thread_grp_synth_top_classifyLinear_fu_193_example_3_value_q0();
    void thread_grp_synth_top_classifyLinear_fu_193_nonZeroFeature_q0();
    void thread_grp_synth_top_classifyLinear_fu_193_weight_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_ap_start();
    void thread_grp_synth_top_classifyPoly_fu_149_example_0_id_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_example_0_value_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_example_1_id_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_example_1_value_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_example_2_id_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_example_2_value_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_example_3_id_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_example_3_value_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_lambda_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_nonZeroFeature_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_output_r_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_sv_0_id_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_sv_0_value_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_sv_1_id_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_sv_1_value_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_sv_2_id_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_sv_2_value_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_sv_3_id_q0();
    void thread_grp_synth_top_classifyPoly_fu_149_sv_3_value_q0();
    void thread_lambda_address0();
    void thread_lambda_ce0();
    void thread_nonZeroFeature_address0();
    void thread_nonZeroFeature_ce0();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_svNonZeroFeature_address0();
    void thread_svNonZeroFeature_ce0();
    void thread_sv_0_id_address0();
    void thread_sv_0_id_ce0();
    void thread_sv_0_value_address0();
    void thread_sv_0_value_ce0();
    void thread_sv_1_id_address0();
    void thread_sv_1_id_ce0();
    void thread_sv_1_value_address0();
    void thread_sv_1_value_ce0();
    void thread_sv_2_id_address0();
    void thread_sv_2_id_ce0();
    void thread_sv_2_value_address0();
    void thread_sv_2_value_ce0();
    void thread_sv_3_id_address0();
    void thread_sv_3_id_ce0();
    void thread_sv_3_value_address0();
    void thread_sv_3_value_ce0();
    void thread_tmp_1_fu_225_p2();
    void thread_tmp_fu_219_p2();
    void thread_weight_address0();
    void thread_weight_ce0();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
