// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _synth_top_classifyLinear_HH_
#define _synth_top_classifyLinear_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "synth_top_fptrunc_64ns_32_1.h"
#include "synth_top_fpext_32ns_64_1.h"
#include "synth_top_dadd_64ns_64ns_64_5_full_dsp.h"
#include "synth_top_dmul_64ns_64ns_64_6_max_dsp.h"

namespace ap_rtl {

struct synth_top_classifyLinear : public sc_module {
    // Port declarations 40
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<10> > example_0_id_address0;
    sc_out< sc_logic > example_0_id_ce0;
    sc_in< sc_lv<32> > example_0_id_q0;
    sc_out< sc_lv<10> > example_1_id_address0;
    sc_out< sc_logic > example_1_id_ce0;
    sc_in< sc_lv<32> > example_1_id_q0;
    sc_out< sc_lv<10> > example_2_id_address0;
    sc_out< sc_logic > example_2_id_ce0;
    sc_in< sc_lv<32> > example_2_id_q0;
    sc_out< sc_lv<10> > example_3_id_address0;
    sc_out< sc_logic > example_3_id_ce0;
    sc_in< sc_lv<32> > example_3_id_q0;
    sc_out< sc_lv<10> > example_0_value_address0;
    sc_out< sc_logic > example_0_value_ce0;
    sc_in< sc_lv<64> > example_0_value_q0;
    sc_out< sc_lv<10> > example_1_value_address0;
    sc_out< sc_logic > example_1_value_ce0;
    sc_in< sc_lv<64> > example_1_value_q0;
    sc_out< sc_lv<10> > example_2_value_address0;
    sc_out< sc_logic > example_2_value_ce0;
    sc_in< sc_lv<64> > example_2_value_q0;
    sc_out< sc_lv<10> > example_3_value_address0;
    sc_out< sc_logic > example_3_value_ce0;
    sc_in< sc_lv<64> > example_3_value_q0;
    sc_out< sc_lv<6> > nonZeroFeature_address0;
    sc_out< sc_logic > nonZeroFeature_ce0;
    sc_in< sc_lv<32> > nonZeroFeature_q0;
    sc_out< sc_lv<6> > weight_address0;
    sc_out< sc_logic > weight_ce0;
    sc_in< sc_lv<64> > weight_q0;
    sc_out< sc_lv<6> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<64> > output_r_d0;


    // Module declarations
    synth_top_classifyLinear(sc_module_name name);
    SC_HAS_PROCESS(synth_top_classifyLinear);

    ~synth_top_classifyLinear();

    sc_trace_file* mVcdFile;

    synth_top_fptrunc_64ns_32_1<1,1,64,32>* synth_top_fptrunc_64ns_32_1_U52;
    synth_top_fpext_32ns_64_1<1,1,32,64>* synth_top_fpext_32ns_64_1_U53;
    synth_top_dadd_64ns_64ns_64_5_full_dsp<1,5,64,64,64>* synth_top_dadd_64ns_64ns_64_5_full_dsp_U54;
    synth_top_dmul_64ns_64ns_64_6_max_dsp<1,6,64,64,64>* synth_top_dmul_64ns_64ns_64_6_max_dsp_U55;
    sc_signal< sc_lv<20> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_38;
    sc_signal< sc_lv<64> > tmp_fu_336_p1;
    sc_signal< sc_lv<64> > tmp_reg_550;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_106;
    sc_signal< sc_lv<1> > exitcond_fu_330_p2;
    sc_signal< sc_lv<32> > nonZeroFeature_load_reg_560;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_bdd_120;
    sc_signal< sc_lv<1> > tmp_2_fu_345_p2;
    sc_signal< sc_lv<1> > tmp_2_reg_565;
    sc_signal< sc_lv<33> > tmp_3_cast_fu_357_p1;
    sc_signal< sc_lv<33> > tmp_3_cast_reg_569;
    sc_signal< sc_lv<2> > tmp_11_fu_387_p1;
    sc_signal< sc_lv<2> > tmp_11_reg_577;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_bdd_135;
    sc_signal< sc_lv<1> > tmp_5_fu_372_p2;
    sc_signal< sc_lv<6> > i_fu_413_p2;
    sc_signal< sc_lv<6> > i_reg_624;
    sc_signal< sc_lv<32> > a2_fu_450_p3;
    sc_signal< sc_lv<32> > a2_reg_629;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_bdd_171;
    sc_signal< sc_lv<64> > example_value_load_phi_fu_479_p3;
    sc_signal< sc_lv<64> > example_value_load_phi_reg_640;
    sc_signal< sc_lv<1> > tmp_7_fu_487_p2;
    sc_signal< sc_lv<1> > tmp_7_reg_645;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_bdd_184;
    sc_signal< sc_lv<64> > weight_load_reg_650;
    sc_signal< sc_lv<32> > p1_2_fu_525_p3;
    sc_signal< sc_lv<32> > p1_2_reg_655;
    sc_signal< sc_lv<32> > p2_2_fu_533_p3;
    sc_signal< sc_lv<32> > p2_2_reg_660;
    sc_signal< sc_lv<64> > grp_fu_326_p2;
    sc_signal< sc_lv<64> > tmp_9_reg_665;
    sc_signal< sc_logic > ap_sig_cseq_ST_st12_fsm_11;
    sc_signal< bool > ap_sig_bdd_198;
    sc_signal< sc_lv<64> > grp_fu_321_p2;
    sc_signal< sc_lv<64> > dot_reg_670;
    sc_signal< sc_logic > ap_sig_cseq_ST_st17_fsm_16;
    sc_signal< bool > ap_sig_bdd_210;
    sc_signal< sc_lv<64> > dot_1_fu_541_p3;
    sc_signal< sc_logic > ap_sig_cseq_ST_st18_fsm_17;
    sc_signal< bool > ap_sig_bdd_220;
    sc_signal< sc_lv<32> > temp_fu_313_p1;
    sc_signal< sc_lv<32> > temp_reg_680;
    sc_signal< sc_logic > ap_sig_cseq_ST_st19_fsm_18;
    sc_signal< bool > ap_sig_bdd_229;
    sc_signal< sc_lv<6> > yindex_assign_reg_252;
    sc_signal< sc_logic > ap_sig_cseq_ST_st20_fsm_19;
    sc_signal< bool > ap_sig_bdd_242;
    sc_signal< sc_lv<32> > p1_0_i_reg_264;
    sc_signal< sc_lv<32> > p2_0_i_reg_276;
    sc_signal< sc_lv<64> > dot_0_i_reg_288;
    sc_signal< sc_lv<64> > p_0_i_reg_300;
    sc_signal< sc_lv<64> > tmp_6_fu_401_p1;
    sc_signal< sc_lv<64> > tmp_8_fu_458_p1;
    sc_signal< sc_lv<64> > tmp_1_fu_317_p1;
    sc_signal< sc_lv<64> > temp_fu_313_p0;
    sc_signal< sc_lv<32> > tmp_1_fu_317_p0;
    sc_signal< sc_lv<64> > grp_fu_321_p0;
    sc_signal< sc_lv<64> > grp_fu_321_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st13_fsm_12;
    sc_signal< bool > ap_sig_bdd_271;
    sc_signal< sc_lv<64> > grp_fu_326_p0;
    sc_signal< sc_lv<64> > grp_fu_326_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_bdd_280;
    sc_signal< sc_lv<6> > tmp_3_fu_351_p0;
    sc_signal< sc_lv<13> > tmp_3_fu_351_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_361_p2;
    sc_signal< sc_lv<1> > not_i_fu_366_p2;
    sc_signal< sc_lv<33> > tmp_6_cast_fu_378_p1;
    sc_signal< sc_lv<33> > p_sum_i_fu_382_p2;
    sc_signal< sc_lv<5> > tmp_10_fu_391_p4;
    sc_signal< sc_lv<1> > sel_tmp_fu_419_p2;
    sc_signal< sc_lv<1> > sel_tmp2_fu_432_p2;
    sc_signal< sc_lv<32> > sel_tmp1_fu_424_p3;
    sc_signal< sc_lv<1> > sel_tmp4_fu_445_p2;
    sc_signal< sc_lv<32> > sel_tmp3_fu_437_p3;
    sc_signal< sc_lv<64> > sel_tmp7_fu_463_p3;
    sc_signal< sc_lv<64> > sel_tmp9_fu_471_p3;
    sc_signal< sc_lv<1> > tmp_s_fu_492_p2;
    sc_signal< sc_lv<32> > p1_fu_503_p2;
    sc_signal< sc_lv<32> > p2_fu_497_p2;
    sc_signal< sc_lv<32> > p1_1_fu_509_p3;
    sc_signal< sc_lv<32> > p2_1_fu_517_p3;
    sc_signal< sc_logic > grp_fu_321_ce;
    sc_signal< sc_logic > grp_fu_326_ce;
    sc_signal< sc_lv<20> > ap_NS_fsm;
    sc_signal< sc_lv<13> > tmp_3_fu_351_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<20> ap_ST_st1_fsm_0;
    static const sc_lv<20> ap_ST_st2_fsm_1;
    static const sc_lv<20> ap_ST_st3_fsm_2;
    static const sc_lv<20> ap_ST_st4_fsm_3;
    static const sc_lv<20> ap_ST_st5_fsm_4;
    static const sc_lv<20> ap_ST_st6_fsm_5;
    static const sc_lv<20> ap_ST_st7_fsm_6;
    static const sc_lv<20> ap_ST_st8_fsm_7;
    static const sc_lv<20> ap_ST_st9_fsm_8;
    static const sc_lv<20> ap_ST_st10_fsm_9;
    static const sc_lv<20> ap_ST_st11_fsm_10;
    static const sc_lv<20> ap_ST_st12_fsm_11;
    static const sc_lv<20> ap_ST_st13_fsm_12;
    static const sc_lv<20> ap_ST_st14_fsm_13;
    static const sc_lv<20> ap_ST_st15_fsm_14;
    static const sc_lv<20> ap_ST_st16_fsm_15;
    static const sc_lv<20> ap_ST_st17_fsm_16;
    static const sc_lv<20> ap_ST_st18_fsm_17;
    static const sc_lv<20> ap_ST_st19_fsm_18;
    static const sc_lv<20> ap_ST_st20_fsm_19;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<6> ap_const_lv6_33;
    static const sc_lv<13> ap_const_lv13_32;
    static const sc_lv<32> ap_const_lv32_33;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<2> ap_const_lv2_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_a2_fu_450_p3();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_106();
    void thread_ap_sig_bdd_120();
    void thread_ap_sig_bdd_135();
    void thread_ap_sig_bdd_171();
    void thread_ap_sig_bdd_184();
    void thread_ap_sig_bdd_198();
    void thread_ap_sig_bdd_210();
    void thread_ap_sig_bdd_220();
    void thread_ap_sig_bdd_229();
    void thread_ap_sig_bdd_242();
    void thread_ap_sig_bdd_271();
    void thread_ap_sig_bdd_280();
    void thread_ap_sig_bdd_38();
    void thread_ap_sig_cseq_ST_st12_fsm_11();
    void thread_ap_sig_cseq_ST_st13_fsm_12();
    void thread_ap_sig_cseq_ST_st17_fsm_16();
    void thread_ap_sig_cseq_ST_st18_fsm_17();
    void thread_ap_sig_cseq_ST_st19_fsm_18();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st20_fsm_19();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_dot_1_fu_541_p3();
    void thread_example_0_id_address0();
    void thread_example_0_id_ce0();
    void thread_example_0_value_address0();
    void thread_example_0_value_ce0();
    void thread_example_1_id_address0();
    void thread_example_1_id_ce0();
    void thread_example_1_value_address0();
    void thread_example_1_value_ce0();
    void thread_example_2_id_address0();
    void thread_example_2_id_ce0();
    void thread_example_2_value_address0();
    void thread_example_2_value_ce0();
    void thread_example_3_id_address0();
    void thread_example_3_id_ce0();
    void thread_example_3_value_address0();
    void thread_example_3_value_ce0();
    void thread_example_value_load_phi_fu_479_p3();
    void thread_exitcond_fu_330_p2();
    void thread_grp_fu_321_ce();
    void thread_grp_fu_321_p0();
    void thread_grp_fu_321_p1();
    void thread_grp_fu_326_ce();
    void thread_grp_fu_326_p0();
    void thread_grp_fu_326_p1();
    void thread_i_fu_413_p2();
    void thread_nonZeroFeature_address0();
    void thread_nonZeroFeature_ce0();
    void thread_not_i_fu_366_p2();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_p1_1_fu_509_p3();
    void thread_p1_2_fu_525_p3();
    void thread_p1_fu_503_p2();
    void thread_p2_1_fu_517_p3();
    void thread_p2_2_fu_533_p3();
    void thread_p2_fu_497_p2();
    void thread_p_sum_i_fu_382_p2();
    void thread_sel_tmp1_fu_424_p3();
    void thread_sel_tmp2_fu_432_p2();
    void thread_sel_tmp3_fu_437_p3();
    void thread_sel_tmp4_fu_445_p2();
    void thread_sel_tmp7_fu_463_p3();
    void thread_sel_tmp9_fu_471_p3();
    void thread_sel_tmp_fu_419_p2();
    void thread_temp_fu_313_p0();
    void thread_tmp_10_fu_391_p4();
    void thread_tmp_11_fu_387_p1();
    void thread_tmp_1_fu_317_p0();
    void thread_tmp_2_fu_345_p2();
    void thread_tmp_3_cast_fu_357_p1();
    void thread_tmp_3_fu_351_p0();
    void thread_tmp_3_fu_351_p00();
    void thread_tmp_3_fu_351_p2();
    void thread_tmp_4_fu_361_p2();
    void thread_tmp_5_fu_372_p2();
    void thread_tmp_6_cast_fu_378_p1();
    void thread_tmp_6_fu_401_p1();
    void thread_tmp_7_fu_487_p2();
    void thread_tmp_8_fu_458_p1();
    void thread_tmp_fu_336_p1();
    void thread_tmp_s_fu_492_p2();
    void thread_weight_address0();
    void thread_weight_ce0();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
