// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "synth_top_writeResult.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic synth_top_writeResult::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic synth_top_writeResult::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> synth_top_writeResult::ap_ST_st1_fsm_0 = "1";
const sc_lv<2> synth_top_writeResult::ap_ST_st2_fsm_1 = "10";
const sc_lv<32> synth_top_writeResult::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> synth_top_writeResult::ap_const_lv1_1 = "1";
const sc_lv<1> synth_top_writeResult::ap_const_lv1_0 = "0";
const sc_lv<32> synth_top_writeResult::ap_const_lv32_1 = "1";

synth_top_writeResult::synth_top_writeResult(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_synth_top_classifyPoly_fu_149 = new synth_top_classifyPoly("grp_synth_top_classifyPoly_fu_149");
    grp_synth_top_classifyPoly_fu_149->ap_clk(ap_clk);
    grp_synth_top_classifyPoly_fu_149->ap_rst(ap_rst);
    grp_synth_top_classifyPoly_fu_149->ap_start(grp_synth_top_classifyPoly_fu_149_ap_start);
    grp_synth_top_classifyPoly_fu_149->ap_done(grp_synth_top_classifyPoly_fu_149_ap_done);
    grp_synth_top_classifyPoly_fu_149->ap_idle(grp_synth_top_classifyPoly_fu_149_ap_idle);
    grp_synth_top_classifyPoly_fu_149->ap_ready(grp_synth_top_classifyPoly_fu_149_ap_ready);
    grp_synth_top_classifyPoly_fu_149->example_0_id_address0(grp_synth_top_classifyPoly_fu_149_example_0_id_address0);
    grp_synth_top_classifyPoly_fu_149->example_0_id_ce0(grp_synth_top_classifyPoly_fu_149_example_0_id_ce0);
    grp_synth_top_classifyPoly_fu_149->example_0_id_q0(grp_synth_top_classifyPoly_fu_149_example_0_id_q0);
    grp_synth_top_classifyPoly_fu_149->example_1_id_address0(grp_synth_top_classifyPoly_fu_149_example_1_id_address0);
    grp_synth_top_classifyPoly_fu_149->example_1_id_ce0(grp_synth_top_classifyPoly_fu_149_example_1_id_ce0);
    grp_synth_top_classifyPoly_fu_149->example_1_id_q0(grp_synth_top_classifyPoly_fu_149_example_1_id_q0);
    grp_synth_top_classifyPoly_fu_149->example_2_id_address0(grp_synth_top_classifyPoly_fu_149_example_2_id_address0);
    grp_synth_top_classifyPoly_fu_149->example_2_id_ce0(grp_synth_top_classifyPoly_fu_149_example_2_id_ce0);
    grp_synth_top_classifyPoly_fu_149->example_2_id_q0(grp_synth_top_classifyPoly_fu_149_example_2_id_q0);
    grp_synth_top_classifyPoly_fu_149->example_3_id_address0(grp_synth_top_classifyPoly_fu_149_example_3_id_address0);
    grp_synth_top_classifyPoly_fu_149->example_3_id_ce0(grp_synth_top_classifyPoly_fu_149_example_3_id_ce0);
    grp_synth_top_classifyPoly_fu_149->example_3_id_q0(grp_synth_top_classifyPoly_fu_149_example_3_id_q0);
    grp_synth_top_classifyPoly_fu_149->example_0_value_address0(grp_synth_top_classifyPoly_fu_149_example_0_value_address0);
    grp_synth_top_classifyPoly_fu_149->example_0_value_ce0(grp_synth_top_classifyPoly_fu_149_example_0_value_ce0);
    grp_synth_top_classifyPoly_fu_149->example_0_value_q0(grp_synth_top_classifyPoly_fu_149_example_0_value_q0);
    grp_synth_top_classifyPoly_fu_149->example_1_value_address0(grp_synth_top_classifyPoly_fu_149_example_1_value_address0);
    grp_synth_top_classifyPoly_fu_149->example_1_value_ce0(grp_synth_top_classifyPoly_fu_149_example_1_value_ce0);
    grp_synth_top_classifyPoly_fu_149->example_1_value_q0(grp_synth_top_classifyPoly_fu_149_example_1_value_q0);
    grp_synth_top_classifyPoly_fu_149->example_2_value_address0(grp_synth_top_classifyPoly_fu_149_example_2_value_address0);
    grp_synth_top_classifyPoly_fu_149->example_2_value_ce0(grp_synth_top_classifyPoly_fu_149_example_2_value_ce0);
    grp_synth_top_classifyPoly_fu_149->example_2_value_q0(grp_synth_top_classifyPoly_fu_149_example_2_value_q0);
    grp_synth_top_classifyPoly_fu_149->example_3_value_address0(grp_synth_top_classifyPoly_fu_149_example_3_value_address0);
    grp_synth_top_classifyPoly_fu_149->example_3_value_ce0(grp_synth_top_classifyPoly_fu_149_example_3_value_ce0);
    grp_synth_top_classifyPoly_fu_149->example_3_value_q0(grp_synth_top_classifyPoly_fu_149_example_3_value_q0);
    grp_synth_top_classifyPoly_fu_149->sv_0_id_address0(grp_synth_top_classifyPoly_fu_149_sv_0_id_address0);
    grp_synth_top_classifyPoly_fu_149->sv_0_id_ce0(grp_synth_top_classifyPoly_fu_149_sv_0_id_ce0);
    grp_synth_top_classifyPoly_fu_149->sv_0_id_q0(grp_synth_top_classifyPoly_fu_149_sv_0_id_q0);
    grp_synth_top_classifyPoly_fu_149->sv_1_id_address0(grp_synth_top_classifyPoly_fu_149_sv_1_id_address0);
    grp_synth_top_classifyPoly_fu_149->sv_1_id_ce0(grp_synth_top_classifyPoly_fu_149_sv_1_id_ce0);
    grp_synth_top_classifyPoly_fu_149->sv_1_id_q0(grp_synth_top_classifyPoly_fu_149_sv_1_id_q0);
    grp_synth_top_classifyPoly_fu_149->sv_2_id_address0(grp_synth_top_classifyPoly_fu_149_sv_2_id_address0);
    grp_synth_top_classifyPoly_fu_149->sv_2_id_ce0(grp_synth_top_classifyPoly_fu_149_sv_2_id_ce0);
    grp_synth_top_classifyPoly_fu_149->sv_2_id_q0(grp_synth_top_classifyPoly_fu_149_sv_2_id_q0);
    grp_synth_top_classifyPoly_fu_149->sv_3_id_address0(grp_synth_top_classifyPoly_fu_149_sv_3_id_address0);
    grp_synth_top_classifyPoly_fu_149->sv_3_id_ce0(grp_synth_top_classifyPoly_fu_149_sv_3_id_ce0);
    grp_synth_top_classifyPoly_fu_149->sv_3_id_q0(grp_synth_top_classifyPoly_fu_149_sv_3_id_q0);
    grp_synth_top_classifyPoly_fu_149->sv_0_value_address0(grp_synth_top_classifyPoly_fu_149_sv_0_value_address0);
    grp_synth_top_classifyPoly_fu_149->sv_0_value_ce0(grp_synth_top_classifyPoly_fu_149_sv_0_value_ce0);
    grp_synth_top_classifyPoly_fu_149->sv_0_value_q0(grp_synth_top_classifyPoly_fu_149_sv_0_value_q0);
    grp_synth_top_classifyPoly_fu_149->sv_1_value_address0(grp_synth_top_classifyPoly_fu_149_sv_1_value_address0);
    grp_synth_top_classifyPoly_fu_149->sv_1_value_ce0(grp_synth_top_classifyPoly_fu_149_sv_1_value_ce0);
    grp_synth_top_classifyPoly_fu_149->sv_1_value_q0(grp_synth_top_classifyPoly_fu_149_sv_1_value_q0);
    grp_synth_top_classifyPoly_fu_149->sv_2_value_address0(grp_synth_top_classifyPoly_fu_149_sv_2_value_address0);
    grp_synth_top_classifyPoly_fu_149->sv_2_value_ce0(grp_synth_top_classifyPoly_fu_149_sv_2_value_ce0);
    grp_synth_top_classifyPoly_fu_149->sv_2_value_q0(grp_synth_top_classifyPoly_fu_149_sv_2_value_q0);
    grp_synth_top_classifyPoly_fu_149->sv_3_value_address0(grp_synth_top_classifyPoly_fu_149_sv_3_value_address0);
    grp_synth_top_classifyPoly_fu_149->sv_3_value_ce0(grp_synth_top_classifyPoly_fu_149_sv_3_value_ce0);
    grp_synth_top_classifyPoly_fu_149->sv_3_value_q0(grp_synth_top_classifyPoly_fu_149_sv_3_value_q0);
    grp_synth_top_classifyPoly_fu_149->lambda_address0(grp_synth_top_classifyPoly_fu_149_lambda_address0);
    grp_synth_top_classifyPoly_fu_149->lambda_ce0(grp_synth_top_classifyPoly_fu_149_lambda_ce0);
    grp_synth_top_classifyPoly_fu_149->lambda_q0(grp_synth_top_classifyPoly_fu_149_lambda_q0);
    grp_synth_top_classifyPoly_fu_149->svNonZeroFeature_address0(grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_address0);
    grp_synth_top_classifyPoly_fu_149->svNonZeroFeature_ce0(grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_ce0);
    grp_synth_top_classifyPoly_fu_149->svNonZeroFeature_q0(grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_q0);
    grp_synth_top_classifyPoly_fu_149->nonZeroFeature_address0(grp_synth_top_classifyPoly_fu_149_nonZeroFeature_address0);
    grp_synth_top_classifyPoly_fu_149->nonZeroFeature_ce0(grp_synth_top_classifyPoly_fu_149_nonZeroFeature_ce0);
    grp_synth_top_classifyPoly_fu_149->nonZeroFeature_q0(grp_synth_top_classifyPoly_fu_149_nonZeroFeature_q0);
    grp_synth_top_classifyPoly_fu_149->output_r_address0(grp_synth_top_classifyPoly_fu_149_output_r_address0);
    grp_synth_top_classifyPoly_fu_149->output_r_ce0(grp_synth_top_classifyPoly_fu_149_output_r_ce0);
    grp_synth_top_classifyPoly_fu_149->output_r_we0(grp_synth_top_classifyPoly_fu_149_output_r_we0);
    grp_synth_top_classifyPoly_fu_149->output_r_d0(grp_synth_top_classifyPoly_fu_149_output_r_d0);
    grp_synth_top_classifyPoly_fu_149->output_r_q0(grp_synth_top_classifyPoly_fu_149_output_r_q0);
    grp_synth_top_classifyLinear_fu_193 = new synth_top_classifyLinear("grp_synth_top_classifyLinear_fu_193");
    grp_synth_top_classifyLinear_fu_193->ap_clk(ap_clk);
    grp_synth_top_classifyLinear_fu_193->ap_rst(ap_rst);
    grp_synth_top_classifyLinear_fu_193->ap_start(grp_synth_top_classifyLinear_fu_193_ap_start);
    grp_synth_top_classifyLinear_fu_193->ap_done(grp_synth_top_classifyLinear_fu_193_ap_done);
    grp_synth_top_classifyLinear_fu_193->ap_idle(grp_synth_top_classifyLinear_fu_193_ap_idle);
    grp_synth_top_classifyLinear_fu_193->ap_ready(grp_synth_top_classifyLinear_fu_193_ap_ready);
    grp_synth_top_classifyLinear_fu_193->example_0_id_address0(grp_synth_top_classifyLinear_fu_193_example_0_id_address0);
    grp_synth_top_classifyLinear_fu_193->example_0_id_ce0(grp_synth_top_classifyLinear_fu_193_example_0_id_ce0);
    grp_synth_top_classifyLinear_fu_193->example_0_id_q0(grp_synth_top_classifyLinear_fu_193_example_0_id_q0);
    grp_synth_top_classifyLinear_fu_193->example_1_id_address0(grp_synth_top_classifyLinear_fu_193_example_1_id_address0);
    grp_synth_top_classifyLinear_fu_193->example_1_id_ce0(grp_synth_top_classifyLinear_fu_193_example_1_id_ce0);
    grp_synth_top_classifyLinear_fu_193->example_1_id_q0(grp_synth_top_classifyLinear_fu_193_example_1_id_q0);
    grp_synth_top_classifyLinear_fu_193->example_2_id_address0(grp_synth_top_classifyLinear_fu_193_example_2_id_address0);
    grp_synth_top_classifyLinear_fu_193->example_2_id_ce0(grp_synth_top_classifyLinear_fu_193_example_2_id_ce0);
    grp_synth_top_classifyLinear_fu_193->example_2_id_q0(grp_synth_top_classifyLinear_fu_193_example_2_id_q0);
    grp_synth_top_classifyLinear_fu_193->example_3_id_address0(grp_synth_top_classifyLinear_fu_193_example_3_id_address0);
    grp_synth_top_classifyLinear_fu_193->example_3_id_ce0(grp_synth_top_classifyLinear_fu_193_example_3_id_ce0);
    grp_synth_top_classifyLinear_fu_193->example_3_id_q0(grp_synth_top_classifyLinear_fu_193_example_3_id_q0);
    grp_synth_top_classifyLinear_fu_193->example_0_value_address0(grp_synth_top_classifyLinear_fu_193_example_0_value_address0);
    grp_synth_top_classifyLinear_fu_193->example_0_value_ce0(grp_synth_top_classifyLinear_fu_193_example_0_value_ce0);
    grp_synth_top_classifyLinear_fu_193->example_0_value_q0(grp_synth_top_classifyLinear_fu_193_example_0_value_q0);
    grp_synth_top_classifyLinear_fu_193->example_1_value_address0(grp_synth_top_classifyLinear_fu_193_example_1_value_address0);
    grp_synth_top_classifyLinear_fu_193->example_1_value_ce0(grp_synth_top_classifyLinear_fu_193_example_1_value_ce0);
    grp_synth_top_classifyLinear_fu_193->example_1_value_q0(grp_synth_top_classifyLinear_fu_193_example_1_value_q0);
    grp_synth_top_classifyLinear_fu_193->example_2_value_address0(grp_synth_top_classifyLinear_fu_193_example_2_value_address0);
    grp_synth_top_classifyLinear_fu_193->example_2_value_ce0(grp_synth_top_classifyLinear_fu_193_example_2_value_ce0);
    grp_synth_top_classifyLinear_fu_193->example_2_value_q0(grp_synth_top_classifyLinear_fu_193_example_2_value_q0);
    grp_synth_top_classifyLinear_fu_193->example_3_value_address0(grp_synth_top_classifyLinear_fu_193_example_3_value_address0);
    grp_synth_top_classifyLinear_fu_193->example_3_value_ce0(grp_synth_top_classifyLinear_fu_193_example_3_value_ce0);
    grp_synth_top_classifyLinear_fu_193->example_3_value_q0(grp_synth_top_classifyLinear_fu_193_example_3_value_q0);
    grp_synth_top_classifyLinear_fu_193->nonZeroFeature_address0(grp_synth_top_classifyLinear_fu_193_nonZeroFeature_address0);
    grp_synth_top_classifyLinear_fu_193->nonZeroFeature_ce0(grp_synth_top_classifyLinear_fu_193_nonZeroFeature_ce0);
    grp_synth_top_classifyLinear_fu_193->nonZeroFeature_q0(grp_synth_top_classifyLinear_fu_193_nonZeroFeature_q0);
    grp_synth_top_classifyLinear_fu_193->weight_address0(grp_synth_top_classifyLinear_fu_193_weight_address0);
    grp_synth_top_classifyLinear_fu_193->weight_ce0(grp_synth_top_classifyLinear_fu_193_weight_ce0);
    grp_synth_top_classifyLinear_fu_193->weight_q0(grp_synth_top_classifyLinear_fu_193_weight_q0);
    grp_synth_top_classifyLinear_fu_193->output_r_address0(grp_synth_top_classifyLinear_fu_193_output_r_address0);
    grp_synth_top_classifyLinear_fu_193->output_r_ce0(grp_synth_top_classifyLinear_fu_193_output_r_ce0);
    grp_synth_top_classifyLinear_fu_193->output_r_we0(grp_synth_top_classifyLinear_fu_193_output_r_we0);
    grp_synth_top_classifyLinear_fu_193->output_r_d0(grp_synth_top_classifyLinear_fu_193_output_r_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_ap_done );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_ap_done );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_141);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_268);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_274);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_268 );

    SC_METHOD(thread_example_0_id_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_0_id_address0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_0_id_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_0_id_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_0_id_ce0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_0_id_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_0_value_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_0_value_address0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_0_value_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_0_value_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_0_value_ce0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_0_value_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_1_id_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_1_id_address0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_1_id_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_1_id_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_1_id_ce0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_1_id_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_1_value_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_1_value_address0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_1_value_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_1_value_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_1_value_ce0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_1_value_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_2_id_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_2_id_address0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_2_id_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_2_id_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_2_id_ce0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_2_id_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_2_value_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_2_value_address0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_2_value_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_2_value_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_2_value_ce0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_2_value_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_3_id_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_3_id_address0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_3_id_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_3_id_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_3_id_ce0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_3_id_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_3_value_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_3_value_address0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_3_value_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_example_3_value_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_example_3_value_ce0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_example_3_value_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_grp_synth_top_classifyLinear_fu_193_ap_start);
    sensitive << ( grp_synth_top_classifyLinear_fu_193_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_synth_top_classifyLinear_fu_193_example_0_id_q0);
    sensitive << ( example_0_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyLinear_fu_193_example_0_value_q0);
    sensitive << ( example_0_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyLinear_fu_193_example_1_id_q0);
    sensitive << ( example_1_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyLinear_fu_193_example_1_value_q0);
    sensitive << ( example_1_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyLinear_fu_193_example_2_id_q0);
    sensitive << ( example_2_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyLinear_fu_193_example_2_value_q0);
    sensitive << ( example_2_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyLinear_fu_193_example_3_id_q0);
    sensitive << ( example_3_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyLinear_fu_193_example_3_value_q0);
    sensitive << ( example_3_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyLinear_fu_193_nonZeroFeature_q0);
    sensitive << ( nonZeroFeature_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyLinear_fu_193_weight_q0);
    sensitive << ( weight_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_ap_start);
    sensitive << ( grp_synth_top_classifyPoly_fu_149_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_example_0_id_q0);
    sensitive << ( example_0_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_example_0_value_q0);
    sensitive << ( example_0_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_example_1_id_q0);
    sensitive << ( example_1_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_example_1_value_q0);
    sensitive << ( example_1_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_example_2_id_q0);
    sensitive << ( example_2_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_example_2_value_q0);
    sensitive << ( example_2_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_example_3_id_q0);
    sensitive << ( example_3_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_example_3_value_q0);
    sensitive << ( example_3_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_lambda_q0);
    sensitive << ( lambda_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_nonZeroFeature_q0);
    sensitive << ( nonZeroFeature_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_output_r_q0);
    sensitive << ( output_r_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_q0);
    sensitive << ( svNonZeroFeature_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_sv_0_id_q0);
    sensitive << ( sv_0_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_sv_0_value_q0);
    sensitive << ( sv_0_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_sv_1_id_q0);
    sensitive << ( sv_1_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_sv_1_value_q0);
    sensitive << ( sv_1_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_sv_2_id_q0);
    sensitive << ( sv_2_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_sv_2_value_q0);
    sensitive << ( sv_2_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_sv_3_id_q0);
    sensitive << ( sv_3_id_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_synth_top_classifyPoly_fu_149_sv_3_value_q0);
    sensitive << ( sv_3_value_q0 );
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_lambda_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_lambda_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_lambda_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_lambda_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_nonZeroFeature_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_nonZeroFeature_address0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_nonZeroFeature_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_nonZeroFeature_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_nonZeroFeature_ce0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_nonZeroFeature_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_output_r_address0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_output_r_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_output_r_ce0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_output_r_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_output_r_d0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_output_r_d0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_output_r_we0 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_output_r_we0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_bdd_274 );

    SC_METHOD(thread_svNonZeroFeature_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_svNonZeroFeature_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_0_id_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_0_id_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_0_id_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_0_id_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_0_value_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_0_value_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_0_value_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_0_value_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_1_id_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_1_id_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_1_id_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_1_id_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_1_value_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_1_value_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_1_value_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_1_value_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_2_id_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_2_id_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_2_id_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_2_id_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_2_value_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_2_value_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_2_value_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_2_value_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_3_id_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_3_id_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_3_id_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_3_id_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_3_value_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_3_value_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sv_3_value_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_sv_3_value_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_tmp_1_fu_225_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( kernelType );
    sensitive << ( tmp_fu_219_p2 );
    sensitive << ( ap_sig_bdd_141 );

    SC_METHOD(thread_tmp_fu_219_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( kernelType );
    sensitive << ( ap_sig_bdd_141 );

    SC_METHOD(thread_weight_address0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_weight_address0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_weight_ce0);
    sensitive << ( tmp_reg_231 );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_weight_ce0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_reg_231 );
    sensitive << ( ap_sig_bdd_141 );
    sensitive << ( tmp_1_reg_235 );
    sensitive << ( grp_synth_top_classifyPoly_fu_149_ap_done );
    sensitive << ( grp_synth_top_classifyLinear_fu_193_ap_done );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    grp_synth_top_classifyPoly_fu_149_ap_start_ap_start_reg = SC_LOGIC_0;
    grp_synth_top_classifyLinear_fu_193_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "synth_top_writeResult_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, example_0_id_address0, "(port)example_0_id_address0");
    sc_trace(mVcdFile, example_0_id_ce0, "(port)example_0_id_ce0");
    sc_trace(mVcdFile, example_0_id_q0, "(port)example_0_id_q0");
    sc_trace(mVcdFile, example_1_id_address0, "(port)example_1_id_address0");
    sc_trace(mVcdFile, example_1_id_ce0, "(port)example_1_id_ce0");
    sc_trace(mVcdFile, example_1_id_q0, "(port)example_1_id_q0");
    sc_trace(mVcdFile, example_2_id_address0, "(port)example_2_id_address0");
    sc_trace(mVcdFile, example_2_id_ce0, "(port)example_2_id_ce0");
    sc_trace(mVcdFile, example_2_id_q0, "(port)example_2_id_q0");
    sc_trace(mVcdFile, example_3_id_address0, "(port)example_3_id_address0");
    sc_trace(mVcdFile, example_3_id_ce0, "(port)example_3_id_ce0");
    sc_trace(mVcdFile, example_3_id_q0, "(port)example_3_id_q0");
    sc_trace(mVcdFile, example_0_value_address0, "(port)example_0_value_address0");
    sc_trace(mVcdFile, example_0_value_ce0, "(port)example_0_value_ce0");
    sc_trace(mVcdFile, example_0_value_q0, "(port)example_0_value_q0");
    sc_trace(mVcdFile, example_1_value_address0, "(port)example_1_value_address0");
    sc_trace(mVcdFile, example_1_value_ce0, "(port)example_1_value_ce0");
    sc_trace(mVcdFile, example_1_value_q0, "(port)example_1_value_q0");
    sc_trace(mVcdFile, example_2_value_address0, "(port)example_2_value_address0");
    sc_trace(mVcdFile, example_2_value_ce0, "(port)example_2_value_ce0");
    sc_trace(mVcdFile, example_2_value_q0, "(port)example_2_value_q0");
    sc_trace(mVcdFile, example_3_value_address0, "(port)example_3_value_address0");
    sc_trace(mVcdFile, example_3_value_ce0, "(port)example_3_value_ce0");
    sc_trace(mVcdFile, example_3_value_q0, "(port)example_3_value_q0");
    sc_trace(mVcdFile, sv_0_id_address0, "(port)sv_0_id_address0");
    sc_trace(mVcdFile, sv_0_id_ce0, "(port)sv_0_id_ce0");
    sc_trace(mVcdFile, sv_0_id_q0, "(port)sv_0_id_q0");
    sc_trace(mVcdFile, sv_1_id_address0, "(port)sv_1_id_address0");
    sc_trace(mVcdFile, sv_1_id_ce0, "(port)sv_1_id_ce0");
    sc_trace(mVcdFile, sv_1_id_q0, "(port)sv_1_id_q0");
    sc_trace(mVcdFile, sv_2_id_address0, "(port)sv_2_id_address0");
    sc_trace(mVcdFile, sv_2_id_ce0, "(port)sv_2_id_ce0");
    sc_trace(mVcdFile, sv_2_id_q0, "(port)sv_2_id_q0");
    sc_trace(mVcdFile, sv_3_id_address0, "(port)sv_3_id_address0");
    sc_trace(mVcdFile, sv_3_id_ce0, "(port)sv_3_id_ce0");
    sc_trace(mVcdFile, sv_3_id_q0, "(port)sv_3_id_q0");
    sc_trace(mVcdFile, sv_0_value_address0, "(port)sv_0_value_address0");
    sc_trace(mVcdFile, sv_0_value_ce0, "(port)sv_0_value_ce0");
    sc_trace(mVcdFile, sv_0_value_q0, "(port)sv_0_value_q0");
    sc_trace(mVcdFile, sv_1_value_address0, "(port)sv_1_value_address0");
    sc_trace(mVcdFile, sv_1_value_ce0, "(port)sv_1_value_ce0");
    sc_trace(mVcdFile, sv_1_value_q0, "(port)sv_1_value_q0");
    sc_trace(mVcdFile, sv_2_value_address0, "(port)sv_2_value_address0");
    sc_trace(mVcdFile, sv_2_value_ce0, "(port)sv_2_value_ce0");
    sc_trace(mVcdFile, sv_2_value_q0, "(port)sv_2_value_q0");
    sc_trace(mVcdFile, sv_3_value_address0, "(port)sv_3_value_address0");
    sc_trace(mVcdFile, sv_3_value_ce0, "(port)sv_3_value_ce0");
    sc_trace(mVcdFile, sv_3_value_q0, "(port)sv_3_value_q0");
    sc_trace(mVcdFile, lambda_address0, "(port)lambda_address0");
    sc_trace(mVcdFile, lambda_ce0, "(port)lambda_ce0");
    sc_trace(mVcdFile, lambda_q0, "(port)lambda_q0");
    sc_trace(mVcdFile, svNonZeroFeature_address0, "(port)svNonZeroFeature_address0");
    sc_trace(mVcdFile, svNonZeroFeature_ce0, "(port)svNonZeroFeature_ce0");
    sc_trace(mVcdFile, svNonZeroFeature_q0, "(port)svNonZeroFeature_q0");
    sc_trace(mVcdFile, nonZeroFeature_address0, "(port)nonZeroFeature_address0");
    sc_trace(mVcdFile, nonZeroFeature_ce0, "(port)nonZeroFeature_ce0");
    sc_trace(mVcdFile, nonZeroFeature_q0, "(port)nonZeroFeature_q0");
    sc_trace(mVcdFile, weight_address0, "(port)weight_address0");
    sc_trace(mVcdFile, weight_ce0, "(port)weight_ce0");
    sc_trace(mVcdFile, weight_q0, "(port)weight_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, output_r_q0, "(port)output_r_q0");
    sc_trace(mVcdFile, kernelType, "(port)kernelType");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_21, "ap_sig_bdd_21");
    sc_trace(mVcdFile, tmp_fu_219_p2, "tmp_fu_219_p2");
    sc_trace(mVcdFile, tmp_reg_231, "tmp_reg_231");
    sc_trace(mVcdFile, ap_sig_bdd_141, "ap_sig_bdd_141");
    sc_trace(mVcdFile, tmp_1_fu_225_p2, "tmp_1_fu_225_p2");
    sc_trace(mVcdFile, tmp_1_reg_235, "tmp_1_reg_235");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_ap_start, "grp_synth_top_classifyPoly_fu_149_ap_start");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_ap_done, "grp_synth_top_classifyPoly_fu_149_ap_done");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_ap_idle, "grp_synth_top_classifyPoly_fu_149_ap_idle");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_ap_ready, "grp_synth_top_classifyPoly_fu_149_ap_ready");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_0_id_address0, "grp_synth_top_classifyPoly_fu_149_example_0_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_0_id_ce0, "grp_synth_top_classifyPoly_fu_149_example_0_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_0_id_q0, "grp_synth_top_classifyPoly_fu_149_example_0_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_1_id_address0, "grp_synth_top_classifyPoly_fu_149_example_1_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_1_id_ce0, "grp_synth_top_classifyPoly_fu_149_example_1_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_1_id_q0, "grp_synth_top_classifyPoly_fu_149_example_1_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_2_id_address0, "grp_synth_top_classifyPoly_fu_149_example_2_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_2_id_ce0, "grp_synth_top_classifyPoly_fu_149_example_2_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_2_id_q0, "grp_synth_top_classifyPoly_fu_149_example_2_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_3_id_address0, "grp_synth_top_classifyPoly_fu_149_example_3_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_3_id_ce0, "grp_synth_top_classifyPoly_fu_149_example_3_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_3_id_q0, "grp_synth_top_classifyPoly_fu_149_example_3_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_0_value_address0, "grp_synth_top_classifyPoly_fu_149_example_0_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_0_value_ce0, "grp_synth_top_classifyPoly_fu_149_example_0_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_0_value_q0, "grp_synth_top_classifyPoly_fu_149_example_0_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_1_value_address0, "grp_synth_top_classifyPoly_fu_149_example_1_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_1_value_ce0, "grp_synth_top_classifyPoly_fu_149_example_1_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_1_value_q0, "grp_synth_top_classifyPoly_fu_149_example_1_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_2_value_address0, "grp_synth_top_classifyPoly_fu_149_example_2_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_2_value_ce0, "grp_synth_top_classifyPoly_fu_149_example_2_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_2_value_q0, "grp_synth_top_classifyPoly_fu_149_example_2_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_3_value_address0, "grp_synth_top_classifyPoly_fu_149_example_3_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_3_value_ce0, "grp_synth_top_classifyPoly_fu_149_example_3_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_example_3_value_q0, "grp_synth_top_classifyPoly_fu_149_example_3_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_0_id_address0, "grp_synth_top_classifyPoly_fu_149_sv_0_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_0_id_ce0, "grp_synth_top_classifyPoly_fu_149_sv_0_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_0_id_q0, "grp_synth_top_classifyPoly_fu_149_sv_0_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_1_id_address0, "grp_synth_top_classifyPoly_fu_149_sv_1_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_1_id_ce0, "grp_synth_top_classifyPoly_fu_149_sv_1_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_1_id_q0, "grp_synth_top_classifyPoly_fu_149_sv_1_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_2_id_address0, "grp_synth_top_classifyPoly_fu_149_sv_2_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_2_id_ce0, "grp_synth_top_classifyPoly_fu_149_sv_2_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_2_id_q0, "grp_synth_top_classifyPoly_fu_149_sv_2_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_3_id_address0, "grp_synth_top_classifyPoly_fu_149_sv_3_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_3_id_ce0, "grp_synth_top_classifyPoly_fu_149_sv_3_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_3_id_q0, "grp_synth_top_classifyPoly_fu_149_sv_3_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_0_value_address0, "grp_synth_top_classifyPoly_fu_149_sv_0_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_0_value_ce0, "grp_synth_top_classifyPoly_fu_149_sv_0_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_0_value_q0, "grp_synth_top_classifyPoly_fu_149_sv_0_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_1_value_address0, "grp_synth_top_classifyPoly_fu_149_sv_1_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_1_value_ce0, "grp_synth_top_classifyPoly_fu_149_sv_1_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_1_value_q0, "grp_synth_top_classifyPoly_fu_149_sv_1_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_2_value_address0, "grp_synth_top_classifyPoly_fu_149_sv_2_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_2_value_ce0, "grp_synth_top_classifyPoly_fu_149_sv_2_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_2_value_q0, "grp_synth_top_classifyPoly_fu_149_sv_2_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_3_value_address0, "grp_synth_top_classifyPoly_fu_149_sv_3_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_3_value_ce0, "grp_synth_top_classifyPoly_fu_149_sv_3_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_sv_3_value_q0, "grp_synth_top_classifyPoly_fu_149_sv_3_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_lambda_address0, "grp_synth_top_classifyPoly_fu_149_lambda_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_lambda_ce0, "grp_synth_top_classifyPoly_fu_149_lambda_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_lambda_q0, "grp_synth_top_classifyPoly_fu_149_lambda_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_address0, "grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_ce0, "grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_q0, "grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_nonZeroFeature_address0, "grp_synth_top_classifyPoly_fu_149_nonZeroFeature_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_nonZeroFeature_ce0, "grp_synth_top_classifyPoly_fu_149_nonZeroFeature_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_nonZeroFeature_q0, "grp_synth_top_classifyPoly_fu_149_nonZeroFeature_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_output_r_address0, "grp_synth_top_classifyPoly_fu_149_output_r_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_output_r_ce0, "grp_synth_top_classifyPoly_fu_149_output_r_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_output_r_we0, "grp_synth_top_classifyPoly_fu_149_output_r_we0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_output_r_d0, "grp_synth_top_classifyPoly_fu_149_output_r_d0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_output_r_q0, "grp_synth_top_classifyPoly_fu_149_output_r_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_ap_start, "grp_synth_top_classifyLinear_fu_193_ap_start");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_ap_done, "grp_synth_top_classifyLinear_fu_193_ap_done");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_ap_idle, "grp_synth_top_classifyLinear_fu_193_ap_idle");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_ap_ready, "grp_synth_top_classifyLinear_fu_193_ap_ready");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_0_id_address0, "grp_synth_top_classifyLinear_fu_193_example_0_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_0_id_ce0, "grp_synth_top_classifyLinear_fu_193_example_0_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_0_id_q0, "grp_synth_top_classifyLinear_fu_193_example_0_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_1_id_address0, "grp_synth_top_classifyLinear_fu_193_example_1_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_1_id_ce0, "grp_synth_top_classifyLinear_fu_193_example_1_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_1_id_q0, "grp_synth_top_classifyLinear_fu_193_example_1_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_2_id_address0, "grp_synth_top_classifyLinear_fu_193_example_2_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_2_id_ce0, "grp_synth_top_classifyLinear_fu_193_example_2_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_2_id_q0, "grp_synth_top_classifyLinear_fu_193_example_2_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_3_id_address0, "grp_synth_top_classifyLinear_fu_193_example_3_id_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_3_id_ce0, "grp_synth_top_classifyLinear_fu_193_example_3_id_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_3_id_q0, "grp_synth_top_classifyLinear_fu_193_example_3_id_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_0_value_address0, "grp_synth_top_classifyLinear_fu_193_example_0_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_0_value_ce0, "grp_synth_top_classifyLinear_fu_193_example_0_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_0_value_q0, "grp_synth_top_classifyLinear_fu_193_example_0_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_1_value_address0, "grp_synth_top_classifyLinear_fu_193_example_1_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_1_value_ce0, "grp_synth_top_classifyLinear_fu_193_example_1_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_1_value_q0, "grp_synth_top_classifyLinear_fu_193_example_1_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_2_value_address0, "grp_synth_top_classifyLinear_fu_193_example_2_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_2_value_ce0, "grp_synth_top_classifyLinear_fu_193_example_2_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_2_value_q0, "grp_synth_top_classifyLinear_fu_193_example_2_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_3_value_address0, "grp_synth_top_classifyLinear_fu_193_example_3_value_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_3_value_ce0, "grp_synth_top_classifyLinear_fu_193_example_3_value_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_example_3_value_q0, "grp_synth_top_classifyLinear_fu_193_example_3_value_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_nonZeroFeature_address0, "grp_synth_top_classifyLinear_fu_193_nonZeroFeature_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_nonZeroFeature_ce0, "grp_synth_top_classifyLinear_fu_193_nonZeroFeature_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_nonZeroFeature_q0, "grp_synth_top_classifyLinear_fu_193_nonZeroFeature_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_weight_address0, "grp_synth_top_classifyLinear_fu_193_weight_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_weight_ce0, "grp_synth_top_classifyLinear_fu_193_weight_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_weight_q0, "grp_synth_top_classifyLinear_fu_193_weight_q0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_output_r_address0, "grp_synth_top_classifyLinear_fu_193_output_r_address0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_output_r_ce0, "grp_synth_top_classifyLinear_fu_193_output_r_ce0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_output_r_we0, "grp_synth_top_classifyLinear_fu_193_output_r_we0");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_output_r_d0, "grp_synth_top_classifyLinear_fu_193_output_r_d0");
    sc_trace(mVcdFile, grp_synth_top_classifyPoly_fu_149_ap_start_ap_start_reg, "grp_synth_top_classifyPoly_fu_149_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_268, "ap_sig_bdd_268");
    sc_trace(mVcdFile, grp_synth_top_classifyLinear_fu_193_ap_start_ap_start_reg, "grp_synth_top_classifyLinear_fu_193_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_274, "ap_sig_bdd_274");
#endif

    }
}

synth_top_writeResult::~synth_top_writeResult() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_synth_top_classifyPoly_fu_149;
    delete grp_synth_top_classifyLinear_fu_193;
}

void synth_top_writeResult::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !((esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_synth_top_classifyPoly_fu_149_ap_done.read())) || (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_synth_top_classifyLinear_fu_193_ap_done.read()))))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_synth_top_classifyLinear_fu_193_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
             !ap_sig_bdd_141.read() && 
             !esl_seteq<1,1,1>(tmp_fu_219_p2.read(), ap_const_lv1_0))) {
            grp_synth_top_classifyLinear_fu_193_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_synth_top_classifyLinear_fu_193_ap_ready.read())) {
            grp_synth_top_classifyLinear_fu_193_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_synth_top_classifyPoly_fu_149_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
             !ap_sig_bdd_141.read() && 
             esl_seteq<1,1,1>(tmp_fu_219_p2.read(), ap_const_lv1_0) && 
             !esl_seteq<1,1,1>(tmp_1_fu_225_p2.read(), ap_const_lv1_0))) {
            grp_synth_top_classifyPoly_fu_149_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_synth_top_classifyPoly_fu_149_ap_ready.read())) {
            grp_synth_top_classifyPoly_fu_149_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !ap_sig_bdd_141.read() && esl_seteq<1,1,1>(tmp_fu_219_p2.read(), ap_const_lv1_0))) {
        tmp_1_reg_235 = tmp_1_fu_225_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !ap_sig_bdd_141.read())) {
        tmp_reg_231 = tmp_fu_219_p2.read();
    }
}

void synth_top_writeResult::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !((esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_synth_top_classifyPoly_fu_149_ap_done.read())) || (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_synth_top_classifyLinear_fu_193_ap_done.read())))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !((esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_synth_top_classifyPoly_fu_149_ap_done.read())) || (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_synth_top_classifyLinear_fu_193_ap_done.read()))))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_ap_sig_bdd_141() {
    ap_sig_bdd_141 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void synth_top_writeResult::thread_ap_sig_bdd_21() {
    ap_sig_bdd_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void synth_top_writeResult::thread_ap_sig_bdd_268() {
    ap_sig_bdd_268 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void synth_top_writeResult::thread_ap_sig_bdd_274() {
    ap_sig_bdd_274 = (esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0));
}

void synth_top_writeResult::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_268.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_example_0_id_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_0_id_address0 = grp_synth_top_classifyLinear_fu_193_example_0_id_address0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_0_id_address0 = grp_synth_top_classifyPoly_fu_149_example_0_id_address0.read();
        } else {
            example_0_id_address0 = "XXXXXXXXXX";
        }
    } else {
        example_0_id_address0 = "XXXXXXXXXX";
    }
}

void synth_top_writeResult::thread_example_0_id_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_0_id_ce0 = grp_synth_top_classifyLinear_fu_193_example_0_id_ce0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_0_id_ce0 = grp_synth_top_classifyPoly_fu_149_example_0_id_ce0.read();
        } else {
            example_0_id_ce0 = ap_const_logic_0;
        }
    } else {
        example_0_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_example_0_value_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_0_value_address0 = grp_synth_top_classifyLinear_fu_193_example_0_value_address0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_0_value_address0 = grp_synth_top_classifyPoly_fu_149_example_0_value_address0.read();
        } else {
            example_0_value_address0 = "XXXXXXXXXX";
        }
    } else {
        example_0_value_address0 = "XXXXXXXXXX";
    }
}

void synth_top_writeResult::thread_example_0_value_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_0_value_ce0 = grp_synth_top_classifyLinear_fu_193_example_0_value_ce0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_0_value_ce0 = grp_synth_top_classifyPoly_fu_149_example_0_value_ce0.read();
        } else {
            example_0_value_ce0 = ap_const_logic_0;
        }
    } else {
        example_0_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_example_1_id_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_1_id_address0 = grp_synth_top_classifyLinear_fu_193_example_1_id_address0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_1_id_address0 = grp_synth_top_classifyPoly_fu_149_example_1_id_address0.read();
        } else {
            example_1_id_address0 = "XXXXXXXXXX";
        }
    } else {
        example_1_id_address0 = "XXXXXXXXXX";
    }
}

void synth_top_writeResult::thread_example_1_id_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_1_id_ce0 = grp_synth_top_classifyLinear_fu_193_example_1_id_ce0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_1_id_ce0 = grp_synth_top_classifyPoly_fu_149_example_1_id_ce0.read();
        } else {
            example_1_id_ce0 = ap_const_logic_0;
        }
    } else {
        example_1_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_example_1_value_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_1_value_address0 = grp_synth_top_classifyLinear_fu_193_example_1_value_address0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_1_value_address0 = grp_synth_top_classifyPoly_fu_149_example_1_value_address0.read();
        } else {
            example_1_value_address0 = "XXXXXXXXXX";
        }
    } else {
        example_1_value_address0 = "XXXXXXXXXX";
    }
}

void synth_top_writeResult::thread_example_1_value_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_1_value_ce0 = grp_synth_top_classifyLinear_fu_193_example_1_value_ce0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_1_value_ce0 = grp_synth_top_classifyPoly_fu_149_example_1_value_ce0.read();
        } else {
            example_1_value_ce0 = ap_const_logic_0;
        }
    } else {
        example_1_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_example_2_id_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_2_id_address0 = grp_synth_top_classifyLinear_fu_193_example_2_id_address0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_2_id_address0 = grp_synth_top_classifyPoly_fu_149_example_2_id_address0.read();
        } else {
            example_2_id_address0 = "XXXXXXXXXX";
        }
    } else {
        example_2_id_address0 = "XXXXXXXXXX";
    }
}

void synth_top_writeResult::thread_example_2_id_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_2_id_ce0 = grp_synth_top_classifyLinear_fu_193_example_2_id_ce0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_2_id_ce0 = grp_synth_top_classifyPoly_fu_149_example_2_id_ce0.read();
        } else {
            example_2_id_ce0 = ap_const_logic_0;
        }
    } else {
        example_2_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_example_2_value_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_2_value_address0 = grp_synth_top_classifyLinear_fu_193_example_2_value_address0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_2_value_address0 = grp_synth_top_classifyPoly_fu_149_example_2_value_address0.read();
        } else {
            example_2_value_address0 = "XXXXXXXXXX";
        }
    } else {
        example_2_value_address0 = "XXXXXXXXXX";
    }
}

void synth_top_writeResult::thread_example_2_value_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_2_value_ce0 = grp_synth_top_classifyLinear_fu_193_example_2_value_ce0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_2_value_ce0 = grp_synth_top_classifyPoly_fu_149_example_2_value_ce0.read();
        } else {
            example_2_value_ce0 = ap_const_logic_0;
        }
    } else {
        example_2_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_example_3_id_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_3_id_address0 = grp_synth_top_classifyLinear_fu_193_example_3_id_address0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_3_id_address0 = grp_synth_top_classifyPoly_fu_149_example_3_id_address0.read();
        } else {
            example_3_id_address0 = "XXXXXXXXXX";
        }
    } else {
        example_3_id_address0 = "XXXXXXXXXX";
    }
}

void synth_top_writeResult::thread_example_3_id_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_3_id_ce0 = grp_synth_top_classifyLinear_fu_193_example_3_id_ce0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_3_id_ce0 = grp_synth_top_classifyPoly_fu_149_example_3_id_ce0.read();
        } else {
            example_3_id_ce0 = ap_const_logic_0;
        }
    } else {
        example_3_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_example_3_value_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_3_value_address0 = grp_synth_top_classifyLinear_fu_193_example_3_value_address0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_3_value_address0 = grp_synth_top_classifyPoly_fu_149_example_3_value_address0.read();
        } else {
            example_3_value_address0 = "XXXXXXXXXX";
        }
    } else {
        example_3_value_address0 = "XXXXXXXXXX";
    }
}

void synth_top_writeResult::thread_example_3_value_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            example_3_value_ce0 = grp_synth_top_classifyLinear_fu_193_example_3_value_ce0.read();
        } else if (ap_sig_bdd_274.read()) {
            example_3_value_ce0 = grp_synth_top_classifyPoly_fu_149_example_3_value_ce0.read();
        } else {
            example_3_value_ce0 = ap_const_logic_0;
        }
    } else {
        example_3_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_grp_synth_top_classifyLinear_fu_193_ap_start() {
    grp_synth_top_classifyLinear_fu_193_ap_start = grp_synth_top_classifyLinear_fu_193_ap_start_ap_start_reg.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyLinear_fu_193_example_0_id_q0() {
    grp_synth_top_classifyLinear_fu_193_example_0_id_q0 = example_0_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyLinear_fu_193_example_0_value_q0() {
    grp_synth_top_classifyLinear_fu_193_example_0_value_q0 = example_0_value_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyLinear_fu_193_example_1_id_q0() {
    grp_synth_top_classifyLinear_fu_193_example_1_id_q0 = example_1_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyLinear_fu_193_example_1_value_q0() {
    grp_synth_top_classifyLinear_fu_193_example_1_value_q0 = example_1_value_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyLinear_fu_193_example_2_id_q0() {
    grp_synth_top_classifyLinear_fu_193_example_2_id_q0 = example_2_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyLinear_fu_193_example_2_value_q0() {
    grp_synth_top_classifyLinear_fu_193_example_2_value_q0 = example_2_value_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyLinear_fu_193_example_3_id_q0() {
    grp_synth_top_classifyLinear_fu_193_example_3_id_q0 = example_3_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyLinear_fu_193_example_3_value_q0() {
    grp_synth_top_classifyLinear_fu_193_example_3_value_q0 = example_3_value_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyLinear_fu_193_nonZeroFeature_q0() {
    grp_synth_top_classifyLinear_fu_193_nonZeroFeature_q0 = nonZeroFeature_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyLinear_fu_193_weight_q0() {
    grp_synth_top_classifyLinear_fu_193_weight_q0 = weight_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_ap_start() {
    grp_synth_top_classifyPoly_fu_149_ap_start = grp_synth_top_classifyPoly_fu_149_ap_start_ap_start_reg.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_example_0_id_q0() {
    grp_synth_top_classifyPoly_fu_149_example_0_id_q0 = example_0_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_example_0_value_q0() {
    grp_synth_top_classifyPoly_fu_149_example_0_value_q0 = example_0_value_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_example_1_id_q0() {
    grp_synth_top_classifyPoly_fu_149_example_1_id_q0 = example_1_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_example_1_value_q0() {
    grp_synth_top_classifyPoly_fu_149_example_1_value_q0 = example_1_value_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_example_2_id_q0() {
    grp_synth_top_classifyPoly_fu_149_example_2_id_q0 = example_2_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_example_2_value_q0() {
    grp_synth_top_classifyPoly_fu_149_example_2_value_q0 = example_2_value_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_example_3_id_q0() {
    grp_synth_top_classifyPoly_fu_149_example_3_id_q0 = example_3_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_example_3_value_q0() {
    grp_synth_top_classifyPoly_fu_149_example_3_value_q0 = example_3_value_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_lambda_q0() {
    grp_synth_top_classifyPoly_fu_149_lambda_q0 = lambda_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_nonZeroFeature_q0() {
    grp_synth_top_classifyPoly_fu_149_nonZeroFeature_q0 = nonZeroFeature_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_output_r_q0() {
    grp_synth_top_classifyPoly_fu_149_output_r_q0 = output_r_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_q0() {
    grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_q0 = svNonZeroFeature_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_sv_0_id_q0() {
    grp_synth_top_classifyPoly_fu_149_sv_0_id_q0 = sv_0_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_sv_0_value_q0() {
    grp_synth_top_classifyPoly_fu_149_sv_0_value_q0 = sv_0_value_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_sv_1_id_q0() {
    grp_synth_top_classifyPoly_fu_149_sv_1_id_q0 = sv_1_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_sv_1_value_q0() {
    grp_synth_top_classifyPoly_fu_149_sv_1_value_q0 = sv_1_value_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_sv_2_id_q0() {
    grp_synth_top_classifyPoly_fu_149_sv_2_id_q0 = sv_2_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_sv_2_value_q0() {
    grp_synth_top_classifyPoly_fu_149_sv_2_value_q0 = sv_2_value_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_sv_3_id_q0() {
    grp_synth_top_classifyPoly_fu_149_sv_3_id_q0 = sv_3_id_q0.read();
}

void synth_top_writeResult::thread_grp_synth_top_classifyPoly_fu_149_sv_3_value_q0() {
    grp_synth_top_classifyPoly_fu_149_sv_3_value_q0 = sv_3_value_q0.read();
}

void synth_top_writeResult::thread_lambda_address0() {
    lambda_address0 = grp_synth_top_classifyPoly_fu_149_lambda_address0.read();
}

void synth_top_writeResult::thread_lambda_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0))) {
        lambda_ce0 = grp_synth_top_classifyPoly_fu_149_lambda_ce0.read();
    } else {
        lambda_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_nonZeroFeature_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            nonZeroFeature_address0 = grp_synth_top_classifyLinear_fu_193_nonZeroFeature_address0.read();
        } else if (ap_sig_bdd_274.read()) {
            nonZeroFeature_address0 = grp_synth_top_classifyPoly_fu_149_nonZeroFeature_address0.read();
        } else {
            nonZeroFeature_address0 =  (sc_lv<6>) ("XXXXXX");
        }
    } else {
        nonZeroFeature_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void synth_top_writeResult::thread_nonZeroFeature_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            nonZeroFeature_ce0 = grp_synth_top_classifyLinear_fu_193_nonZeroFeature_ce0.read();
        } else if (ap_sig_bdd_274.read()) {
            nonZeroFeature_ce0 = grp_synth_top_classifyPoly_fu_149_nonZeroFeature_ce0.read();
        } else {
            nonZeroFeature_ce0 = ap_const_logic_0;
        }
    } else {
        nonZeroFeature_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_output_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            output_r_address0 = grp_synth_top_classifyLinear_fu_193_output_r_address0.read();
        } else if (ap_sig_bdd_274.read()) {
            output_r_address0 = grp_synth_top_classifyPoly_fu_149_output_r_address0.read();
        } else {
            output_r_address0 =  (sc_lv<6>) ("XXXXXX");
        }
    } else {
        output_r_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void synth_top_writeResult::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            output_r_ce0 = grp_synth_top_classifyLinear_fu_193_output_r_ce0.read();
        } else if (ap_sig_bdd_274.read()) {
            output_r_ce0 = grp_synth_top_classifyPoly_fu_149_output_r_ce0.read();
        } else {
            output_r_ce0 = ap_const_logic_0;
        }
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_output_r_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            output_r_d0 = grp_synth_top_classifyLinear_fu_193_output_r_d0.read();
        } else if (ap_sig_bdd_274.read()) {
            output_r_d0 = grp_synth_top_classifyPoly_fu_149_output_r_d0.read();
        } else {
            output_r_d0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        output_r_d0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void synth_top_writeResult::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0)) {
            output_r_we0 = grp_synth_top_classifyLinear_fu_193_output_r_we0.read();
        } else if (ap_sig_bdd_274.read()) {
            output_r_we0 = grp_synth_top_classifyPoly_fu_149_output_r_we0.read();
        } else {
            output_r_we0 = ap_const_logic_0;
        }
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_svNonZeroFeature_address0() {
    svNonZeroFeature_address0 = grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_address0.read();
}

void synth_top_writeResult::thread_svNonZeroFeature_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0))) {
        svNonZeroFeature_ce0 = grp_synth_top_classifyPoly_fu_149_svNonZeroFeature_ce0.read();
    } else {
        svNonZeroFeature_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_sv_0_id_address0() {
    sv_0_id_address0 = grp_synth_top_classifyPoly_fu_149_sv_0_id_address0.read();
}

void synth_top_writeResult::thread_sv_0_id_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0))) {
        sv_0_id_ce0 = grp_synth_top_classifyPoly_fu_149_sv_0_id_ce0.read();
    } else {
        sv_0_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_sv_0_value_address0() {
    sv_0_value_address0 = grp_synth_top_classifyPoly_fu_149_sv_0_value_address0.read();
}

void synth_top_writeResult::thread_sv_0_value_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0))) {
        sv_0_value_ce0 = grp_synth_top_classifyPoly_fu_149_sv_0_value_ce0.read();
    } else {
        sv_0_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_sv_1_id_address0() {
    sv_1_id_address0 = grp_synth_top_classifyPoly_fu_149_sv_1_id_address0.read();
}

void synth_top_writeResult::thread_sv_1_id_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0))) {
        sv_1_id_ce0 = grp_synth_top_classifyPoly_fu_149_sv_1_id_ce0.read();
    } else {
        sv_1_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_sv_1_value_address0() {
    sv_1_value_address0 = grp_synth_top_classifyPoly_fu_149_sv_1_value_address0.read();
}

void synth_top_writeResult::thread_sv_1_value_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0))) {
        sv_1_value_ce0 = grp_synth_top_classifyPoly_fu_149_sv_1_value_ce0.read();
    } else {
        sv_1_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_sv_2_id_address0() {
    sv_2_id_address0 = grp_synth_top_classifyPoly_fu_149_sv_2_id_address0.read();
}

void synth_top_writeResult::thread_sv_2_id_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0))) {
        sv_2_id_ce0 = grp_synth_top_classifyPoly_fu_149_sv_2_id_ce0.read();
    } else {
        sv_2_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_sv_2_value_address0() {
    sv_2_value_address0 = grp_synth_top_classifyPoly_fu_149_sv_2_value_address0.read();
}

void synth_top_writeResult::thread_sv_2_value_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0))) {
        sv_2_value_ce0 = grp_synth_top_classifyPoly_fu_149_sv_2_value_ce0.read();
    } else {
        sv_2_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_sv_3_id_address0() {
    sv_3_id_address0 = grp_synth_top_classifyPoly_fu_149_sv_3_id_address0.read();
}

void synth_top_writeResult::thread_sv_3_id_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0))) {
        sv_3_id_ce0 = grp_synth_top_classifyPoly_fu_149_sv_3_id_ce0.read();
    } else {
        sv_3_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_sv_3_value_address0() {
    sv_3_value_address0 = grp_synth_top_classifyPoly_fu_149_sv_3_value_address0.read();
}

void synth_top_writeResult::thread_sv_3_value_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0))) {
        sv_3_value_ce0 = grp_synth_top_classifyPoly_fu_149_sv_3_value_ce0.read();
    } else {
        sv_3_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_tmp_1_fu_225_p2() {
    tmp_1_fu_225_p2 = (!kernelType.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(kernelType.read() == ap_const_lv32_1);
}

void synth_top_writeResult::thread_tmp_fu_219_p2() {
    tmp_fu_219_p2 = (!kernelType.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(kernelType.read() == ap_const_lv32_0);
}

void synth_top_writeResult::thread_weight_address0() {
    weight_address0 = grp_synth_top_classifyLinear_fu_193_weight_address0.read();
}

void synth_top_writeResult::thread_weight_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0))) {
        weight_ce0 = grp_synth_top_classifyLinear_fu_193_weight_ce0.read();
    } else {
        weight_ce0 = ap_const_logic_0;
    }
}

void synth_top_writeResult::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_141.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!((esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
  !esl_seteq<1,1,1>(tmp_1_reg_235.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_synth_top_classifyPoly_fu_149_ap_done.read())) || (!esl_seteq<1,1,1>(tmp_reg_231.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_synth_top_classifyLinear_fu_193_ap_done.read())))) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

}

