// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "synth_top_classifyLinear.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic synth_top_classifyLinear::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic synth_top_classifyLinear::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<20> synth_top_classifyLinear::ap_ST_st1_fsm_0 = "1";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st2_fsm_1 = "10";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st3_fsm_2 = "100";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st4_fsm_3 = "1000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st5_fsm_4 = "10000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st6_fsm_5 = "100000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<20> synth_top_classifyLinear::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> synth_top_classifyLinear::ap_const_lv1_1 = "1";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_1 = "1";
const sc_lv<1> synth_top_classifyLinear::ap_const_lv1_0 = "0";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_2 = "10";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_3 = "11";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_4 = "100";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_5 = "101";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_B = "1011";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_10 = "10000";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_11 = "10001";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_12 = "10010";
const sc_lv<6> synth_top_classifyLinear::ap_const_lv6_1 = "1";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_13 = "10011";
const sc_lv<64> synth_top_classifyLinear::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_C = "1100";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_6 = "110";
const sc_lv<6> synth_top_classifyLinear::ap_const_lv6_33 = "110011";
const sc_lv<13> synth_top_classifyLinear::ap_const_lv13_32 = "110010";
const sc_lv<32> synth_top_classifyLinear::ap_const_lv32_33 = "110011";
const sc_lv<2> synth_top_classifyLinear::ap_const_lv2_0 = "00";
const sc_lv<2> synth_top_classifyLinear::ap_const_lv2_1 = "1";
const sc_lv<2> synth_top_classifyLinear::ap_const_lv2_2 = "10";

synth_top_classifyLinear::synth_top_classifyLinear(sc_module_name name) : sc_module(name), mVcdFile(0) {
    synth_top_fptrunc_64ns_32_1_U52 = new synth_top_fptrunc_64ns_32_1<1,1,64,32>("synth_top_fptrunc_64ns_32_1_U52");
    synth_top_fptrunc_64ns_32_1_U52->din0(temp_fu_313_p0);
    synth_top_fptrunc_64ns_32_1_U52->dout(temp_fu_313_p1);
    synth_top_fpext_32ns_64_1_U53 = new synth_top_fpext_32ns_64_1<1,1,32,64>("synth_top_fpext_32ns_64_1_U53");
    synth_top_fpext_32ns_64_1_U53->din0(tmp_1_fu_317_p0);
    synth_top_fpext_32ns_64_1_U53->dout(tmp_1_fu_317_p1);
    synth_top_dadd_64ns_64ns_64_5_full_dsp_U54 = new synth_top_dadd_64ns_64ns_64_5_full_dsp<1,5,64,64,64>("synth_top_dadd_64ns_64ns_64_5_full_dsp_U54");
    synth_top_dadd_64ns_64ns_64_5_full_dsp_U54->clk(ap_clk);
    synth_top_dadd_64ns_64ns_64_5_full_dsp_U54->reset(ap_rst);
    synth_top_dadd_64ns_64ns_64_5_full_dsp_U54->din0(grp_fu_321_p0);
    synth_top_dadd_64ns_64ns_64_5_full_dsp_U54->din1(grp_fu_321_p1);
    synth_top_dadd_64ns_64ns_64_5_full_dsp_U54->ce(grp_fu_321_ce);
    synth_top_dadd_64ns_64ns_64_5_full_dsp_U54->dout(grp_fu_321_p2);
    synth_top_dmul_64ns_64ns_64_6_max_dsp_U55 = new synth_top_dmul_64ns_64ns_64_6_max_dsp<1,6,64,64,64>("synth_top_dmul_64ns_64ns_64_6_max_dsp_U55");
    synth_top_dmul_64ns_64ns_64_6_max_dsp_U55->clk(ap_clk);
    synth_top_dmul_64ns_64ns_64_6_max_dsp_U55->reset(ap_rst);
    synth_top_dmul_64ns_64ns_64_6_max_dsp_U55->din0(grp_fu_326_p0);
    synth_top_dmul_64ns_64ns_64_6_max_dsp_U55->din1(grp_fu_326_p1);
    synth_top_dmul_64ns_64ns_64_6_max_dsp_U55->ce(grp_fu_326_ce);
    synth_top_dmul_64ns_64ns_64_6_max_dsp_U55->dout(grp_fu_326_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a2_fu_450_p3);
    sensitive << ( example_2_id_q0 );
    sensitive << ( sel_tmp4_fu_445_p2 );
    sensitive << ( sel_tmp3_fu_437_p3 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_330_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond_fu_330_p2 );

    SC_METHOD(thread_ap_sig_bdd_106);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_120);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_135);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_171);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_184);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_198);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_210);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_220);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_229);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_242);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_271);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_280);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_bdd_198 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_bdd_271 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_bdd_210 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_bdd_220 );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_bdd_229 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_38 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_bdd_242 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_106 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_120 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_135 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_171 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_184 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_280 );

    SC_METHOD(thread_dot_1_fu_541_p3);
    sensitive << ( tmp_7_reg_645 );
    sensitive << ( dot_reg_670 );
    sensitive << ( dot_0_i_reg_288 );

    SC_METHOD(thread_example_0_id_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_6_fu_401_p1 );

    SC_METHOD(thread_example_0_id_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_example_0_value_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_6_fu_401_p1 );

    SC_METHOD(thread_example_0_value_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_example_1_id_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_6_fu_401_p1 );

    SC_METHOD(thread_example_1_id_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_example_1_value_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_6_fu_401_p1 );

    SC_METHOD(thread_example_1_value_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_example_2_id_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_6_fu_401_p1 );

    SC_METHOD(thread_example_2_id_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_example_2_value_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_6_fu_401_p1 );

    SC_METHOD(thread_example_2_value_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_example_3_id_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_6_fu_401_p1 );

    SC_METHOD(thread_example_3_id_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_example_3_value_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_6_fu_401_p1 );

    SC_METHOD(thread_example_3_value_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_example_value_load_phi_fu_479_p3);
    sensitive << ( example_2_value_q0 );
    sensitive << ( sel_tmp4_fu_445_p2 );
    sensitive << ( sel_tmp9_fu_471_p3 );

    SC_METHOD(thread_exitcond_fu_330_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( yindex_assign_reg_252 );

    SC_METHOD(thread_grp_fu_321_ce);

    SC_METHOD(thread_grp_fu_321_p0);
    sensitive << ( dot_0_i_reg_288 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_grp_fu_321_p1);
    sensitive << ( tmp_9_reg_665 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_grp_fu_326_ce);

    SC_METHOD(thread_grp_fu_326_p0);
    sensitive << ( weight_load_reg_650 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_grp_fu_326_p1);
    sensitive << ( example_value_load_phi_reg_640 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_i_fu_413_p2);
    sensitive << ( yindex_assign_reg_252 );

    SC_METHOD(thread_nonZeroFeature_address0);
    sensitive << ( tmp_fu_336_p1 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_nonZeroFeature_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_not_i_fu_366_p2);
    sensitive << ( tmp_2_reg_565 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( p1_0_i_reg_264 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( tmp_reg_550 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( tmp_1_fu_317_p1 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_p1_1_fu_509_p3);
    sensitive << ( p1_0_i_reg_264 );
    sensitive << ( tmp_s_fu_492_p2 );
    sensitive << ( p1_fu_503_p2 );

    SC_METHOD(thread_p1_2_fu_525_p3);
    sensitive << ( tmp_7_fu_487_p2 );
    sensitive << ( p1_fu_503_p2 );
    sensitive << ( p1_1_fu_509_p3 );

    SC_METHOD(thread_p1_fu_503_p2);
    sensitive << ( p1_0_i_reg_264 );

    SC_METHOD(thread_p2_1_fu_517_p3);
    sensitive << ( p2_0_i_reg_276 );
    sensitive << ( tmp_s_fu_492_p2 );
    sensitive << ( p2_fu_497_p2 );

    SC_METHOD(thread_p2_2_fu_533_p3);
    sensitive << ( tmp_7_fu_487_p2 );
    sensitive << ( p2_fu_497_p2 );
    sensitive << ( p2_1_fu_517_p3 );

    SC_METHOD(thread_p2_fu_497_p2);
    sensitive << ( p2_0_i_reg_276 );

    SC_METHOD(thread_p_sum_i_fu_382_p2);
    sensitive << ( tmp_3_cast_reg_569 );
    sensitive << ( tmp_6_cast_fu_378_p1 );

    SC_METHOD(thread_sel_tmp1_fu_424_p3);
    sensitive << ( example_0_id_q0 );
    sensitive << ( example_3_id_q0 );
    sensitive << ( sel_tmp_fu_419_p2 );

    SC_METHOD(thread_sel_tmp2_fu_432_p2);
    sensitive << ( tmp_11_reg_577 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_sel_tmp3_fu_437_p3);
    sensitive << ( example_1_id_q0 );
    sensitive << ( sel_tmp2_fu_432_p2 );
    sensitive << ( sel_tmp1_fu_424_p3 );

    SC_METHOD(thread_sel_tmp4_fu_445_p2);
    sensitive << ( tmp_11_reg_577 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_sel_tmp7_fu_463_p3);
    sensitive << ( example_0_value_q0 );
    sensitive << ( example_3_value_q0 );
    sensitive << ( sel_tmp_fu_419_p2 );

    SC_METHOD(thread_sel_tmp9_fu_471_p3);
    sensitive << ( example_1_value_q0 );
    sensitive << ( sel_tmp2_fu_432_p2 );
    sensitive << ( sel_tmp7_fu_463_p3 );

    SC_METHOD(thread_sel_tmp_fu_419_p2);
    sensitive << ( tmp_11_reg_577 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_temp_fu_313_p0);
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( p_0_i_reg_300 );

    SC_METHOD(thread_tmp_10_fu_391_p4);
    sensitive << ( p_sum_i_fu_382_p2 );

    SC_METHOD(thread_tmp_11_fu_387_p1);
    sensitive << ( p_sum_i_fu_382_p2 );

    SC_METHOD(thread_tmp_1_fu_317_p0);
    sensitive << ( temp_reg_680 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_tmp_2_fu_345_p2);
    sensitive << ( nonZeroFeature_q0 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_tmp_3_cast_fu_357_p1);
    sensitive << ( tmp_3_fu_351_p2 );

    SC_METHOD(thread_tmp_3_fu_351_p0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_3_fu_351_p00 );

    SC_METHOD(thread_tmp_3_fu_351_p00);
    sensitive << ( yindex_assign_reg_252 );

    SC_METHOD(thread_tmp_3_fu_351_p2);
    sensitive << ( tmp_3_fu_351_p0 );

    SC_METHOD(thread_tmp_4_fu_361_p2);
    sensitive << ( nonZeroFeature_load_reg_560 );
    sensitive << ( tmp_2_reg_565 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( p2_0_i_reg_276 );

    SC_METHOD(thread_tmp_5_fu_372_p2);
    sensitive << ( tmp_4_fu_361_p2 );
    sensitive << ( not_i_fu_366_p2 );

    SC_METHOD(thread_tmp_6_cast_fu_378_p1);
    sensitive << ( p2_0_i_reg_276 );

    SC_METHOD(thread_tmp_6_fu_401_p1);
    sensitive << ( tmp_10_fu_391_p4 );

    SC_METHOD(thread_tmp_7_fu_487_p2);
    sensitive << ( a2_reg_629 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( p1_0_i_reg_264 );

    SC_METHOD(thread_tmp_8_fu_458_p1);
    sensitive << ( p1_0_i_reg_264 );

    SC_METHOD(thread_tmp_fu_336_p1);
    sensitive << ( yindex_assign_reg_252 );

    SC_METHOD(thread_tmp_s_fu_492_p2);
    sensitive << ( a2_reg_629 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( p1_0_i_reg_264 );

    SC_METHOD(thread_weight_address0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_8_fu_458_p1 );

    SC_METHOD(thread_weight_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_330_p2 );
    sensitive << ( tmp_2_reg_565 );
    sensitive << ( tmp_5_fu_372_p2 );

    ap_CS_fsm = "00000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "synth_top_classifyLinear_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, example_0_id_address0, "(port)example_0_id_address0");
    sc_trace(mVcdFile, example_0_id_ce0, "(port)example_0_id_ce0");
    sc_trace(mVcdFile, example_0_id_q0, "(port)example_0_id_q0");
    sc_trace(mVcdFile, example_1_id_address0, "(port)example_1_id_address0");
    sc_trace(mVcdFile, example_1_id_ce0, "(port)example_1_id_ce0");
    sc_trace(mVcdFile, example_1_id_q0, "(port)example_1_id_q0");
    sc_trace(mVcdFile, example_2_id_address0, "(port)example_2_id_address0");
    sc_trace(mVcdFile, example_2_id_ce0, "(port)example_2_id_ce0");
    sc_trace(mVcdFile, example_2_id_q0, "(port)example_2_id_q0");
    sc_trace(mVcdFile, example_3_id_address0, "(port)example_3_id_address0");
    sc_trace(mVcdFile, example_3_id_ce0, "(port)example_3_id_ce0");
    sc_trace(mVcdFile, example_3_id_q0, "(port)example_3_id_q0");
    sc_trace(mVcdFile, example_0_value_address0, "(port)example_0_value_address0");
    sc_trace(mVcdFile, example_0_value_ce0, "(port)example_0_value_ce0");
    sc_trace(mVcdFile, example_0_value_q0, "(port)example_0_value_q0");
    sc_trace(mVcdFile, example_1_value_address0, "(port)example_1_value_address0");
    sc_trace(mVcdFile, example_1_value_ce0, "(port)example_1_value_ce0");
    sc_trace(mVcdFile, example_1_value_q0, "(port)example_1_value_q0");
    sc_trace(mVcdFile, example_2_value_address0, "(port)example_2_value_address0");
    sc_trace(mVcdFile, example_2_value_ce0, "(port)example_2_value_ce0");
    sc_trace(mVcdFile, example_2_value_q0, "(port)example_2_value_q0");
    sc_trace(mVcdFile, example_3_value_address0, "(port)example_3_value_address0");
    sc_trace(mVcdFile, example_3_value_ce0, "(port)example_3_value_ce0");
    sc_trace(mVcdFile, example_3_value_q0, "(port)example_3_value_q0");
    sc_trace(mVcdFile, nonZeroFeature_address0, "(port)nonZeroFeature_address0");
    sc_trace(mVcdFile, nonZeroFeature_ce0, "(port)nonZeroFeature_ce0");
    sc_trace(mVcdFile, nonZeroFeature_q0, "(port)nonZeroFeature_q0");
    sc_trace(mVcdFile, weight_address0, "(port)weight_address0");
    sc_trace(mVcdFile, weight_ce0, "(port)weight_ce0");
    sc_trace(mVcdFile, weight_q0, "(port)weight_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_38, "ap_sig_bdd_38");
    sc_trace(mVcdFile, tmp_fu_336_p1, "tmp_fu_336_p1");
    sc_trace(mVcdFile, tmp_reg_550, "tmp_reg_550");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_106, "ap_sig_bdd_106");
    sc_trace(mVcdFile, exitcond_fu_330_p2, "exitcond_fu_330_p2");
    sc_trace(mVcdFile, nonZeroFeature_load_reg_560, "nonZeroFeature_load_reg_560");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_120, "ap_sig_bdd_120");
    sc_trace(mVcdFile, tmp_2_fu_345_p2, "tmp_2_fu_345_p2");
    sc_trace(mVcdFile, tmp_2_reg_565, "tmp_2_reg_565");
    sc_trace(mVcdFile, tmp_3_cast_fu_357_p1, "tmp_3_cast_fu_357_p1");
    sc_trace(mVcdFile, tmp_3_cast_reg_569, "tmp_3_cast_reg_569");
    sc_trace(mVcdFile, tmp_11_fu_387_p1, "tmp_11_fu_387_p1");
    sc_trace(mVcdFile, tmp_11_reg_577, "tmp_11_reg_577");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_135, "ap_sig_bdd_135");
    sc_trace(mVcdFile, tmp_5_fu_372_p2, "tmp_5_fu_372_p2");
    sc_trace(mVcdFile, i_fu_413_p2, "i_fu_413_p2");
    sc_trace(mVcdFile, i_reg_624, "i_reg_624");
    sc_trace(mVcdFile, a2_fu_450_p3, "a2_fu_450_p3");
    sc_trace(mVcdFile, a2_reg_629, "a2_reg_629");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_171, "ap_sig_bdd_171");
    sc_trace(mVcdFile, example_value_load_phi_fu_479_p3, "example_value_load_phi_fu_479_p3");
    sc_trace(mVcdFile, example_value_load_phi_reg_640, "example_value_load_phi_reg_640");
    sc_trace(mVcdFile, tmp_7_fu_487_p2, "tmp_7_fu_487_p2");
    sc_trace(mVcdFile, tmp_7_reg_645, "tmp_7_reg_645");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_184, "ap_sig_bdd_184");
    sc_trace(mVcdFile, weight_load_reg_650, "weight_load_reg_650");
    sc_trace(mVcdFile, p1_2_fu_525_p3, "p1_2_fu_525_p3");
    sc_trace(mVcdFile, p1_2_reg_655, "p1_2_reg_655");
    sc_trace(mVcdFile, p2_2_fu_533_p3, "p2_2_fu_533_p3");
    sc_trace(mVcdFile, p2_2_reg_660, "p2_2_reg_660");
    sc_trace(mVcdFile, grp_fu_326_p2, "grp_fu_326_p2");
    sc_trace(mVcdFile, tmp_9_reg_665, "tmp_9_reg_665");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_bdd_198, "ap_sig_bdd_198");
    sc_trace(mVcdFile, grp_fu_321_p2, "grp_fu_321_p2");
    sc_trace(mVcdFile, dot_reg_670, "dot_reg_670");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_bdd_210, "ap_sig_bdd_210");
    sc_trace(mVcdFile, dot_1_fu_541_p3, "dot_1_fu_541_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_bdd_220, "ap_sig_bdd_220");
    sc_trace(mVcdFile, temp_fu_313_p1, "temp_fu_313_p1");
    sc_trace(mVcdFile, temp_reg_680, "temp_reg_680");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_bdd_229, "ap_sig_bdd_229");
    sc_trace(mVcdFile, yindex_assign_reg_252, "yindex_assign_reg_252");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_bdd_242, "ap_sig_bdd_242");
    sc_trace(mVcdFile, p1_0_i_reg_264, "p1_0_i_reg_264");
    sc_trace(mVcdFile, p2_0_i_reg_276, "p2_0_i_reg_276");
    sc_trace(mVcdFile, dot_0_i_reg_288, "dot_0_i_reg_288");
    sc_trace(mVcdFile, p_0_i_reg_300, "p_0_i_reg_300");
    sc_trace(mVcdFile, tmp_6_fu_401_p1, "tmp_6_fu_401_p1");
    sc_trace(mVcdFile, tmp_8_fu_458_p1, "tmp_8_fu_458_p1");
    sc_trace(mVcdFile, tmp_1_fu_317_p1, "tmp_1_fu_317_p1");
    sc_trace(mVcdFile, temp_fu_313_p0, "temp_fu_313_p0");
    sc_trace(mVcdFile, tmp_1_fu_317_p0, "tmp_1_fu_317_p0");
    sc_trace(mVcdFile, grp_fu_321_p0, "grp_fu_321_p0");
    sc_trace(mVcdFile, grp_fu_321_p1, "grp_fu_321_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_bdd_271, "ap_sig_bdd_271");
    sc_trace(mVcdFile, grp_fu_326_p0, "grp_fu_326_p0");
    sc_trace(mVcdFile, grp_fu_326_p1, "grp_fu_326_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_280, "ap_sig_bdd_280");
    sc_trace(mVcdFile, tmp_3_fu_351_p0, "tmp_3_fu_351_p0");
    sc_trace(mVcdFile, tmp_3_fu_351_p2, "tmp_3_fu_351_p2");
    sc_trace(mVcdFile, tmp_4_fu_361_p2, "tmp_4_fu_361_p2");
    sc_trace(mVcdFile, not_i_fu_366_p2, "not_i_fu_366_p2");
    sc_trace(mVcdFile, tmp_6_cast_fu_378_p1, "tmp_6_cast_fu_378_p1");
    sc_trace(mVcdFile, p_sum_i_fu_382_p2, "p_sum_i_fu_382_p2");
    sc_trace(mVcdFile, tmp_10_fu_391_p4, "tmp_10_fu_391_p4");
    sc_trace(mVcdFile, sel_tmp_fu_419_p2, "sel_tmp_fu_419_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_432_p2, "sel_tmp2_fu_432_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_424_p3, "sel_tmp1_fu_424_p3");
    sc_trace(mVcdFile, sel_tmp4_fu_445_p2, "sel_tmp4_fu_445_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_437_p3, "sel_tmp3_fu_437_p3");
    sc_trace(mVcdFile, sel_tmp7_fu_463_p3, "sel_tmp7_fu_463_p3");
    sc_trace(mVcdFile, sel_tmp9_fu_471_p3, "sel_tmp9_fu_471_p3");
    sc_trace(mVcdFile, tmp_s_fu_492_p2, "tmp_s_fu_492_p2");
    sc_trace(mVcdFile, p1_fu_503_p2, "p1_fu_503_p2");
    sc_trace(mVcdFile, p2_fu_497_p2, "p2_fu_497_p2");
    sc_trace(mVcdFile, p1_1_fu_509_p3, "p1_1_fu_509_p3");
    sc_trace(mVcdFile, p2_1_fu_517_p3, "p2_1_fu_517_p3");
    sc_trace(mVcdFile, grp_fu_321_ce, "grp_fu_321_ce");
    sc_trace(mVcdFile, grp_fu_326_ce, "grp_fu_326_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, tmp_3_fu_351_p00, "tmp_3_fu_351_p00");
#endif

    }
}

synth_top_classifyLinear::~synth_top_classifyLinear() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete synth_top_fptrunc_64ns_32_1_U52;
    delete synth_top_fpext_32ns_64_1_U53;
    delete synth_top_dadd_64ns_64ns_64_5_full_dsp_U54;
    delete synth_top_dmul_64ns_64ns_64_6_max_dsp_U55;
}

void synth_top_classifyLinear::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_345_p2.read()))) {
        dot_0_i_reg_288 = ap_const_lv64_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        dot_0_i_reg_288 = dot_1_fu_541_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_345_p2.read()))) {
        p1_0_i_reg_264 = ap_const_lv32_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        p1_0_i_reg_264 = p1_2_reg_655.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_345_p2.read()))) {
        p2_0_i_reg_276 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        p2_0_i_reg_276 = p2_2_reg_660.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_565.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_372_p2.read()))) {
        p_0_i_reg_300 = dot_0_i_reg_288.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_345_p2.read()))) {
        p_0_i_reg_300 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        yindex_assign_reg_252 = i_reg_624.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        yindex_assign_reg_252 = ap_const_lv6_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        a2_reg_629 = a2_fu_450_p3.read();
        example_value_load_phi_reg_640 = example_value_load_phi_fu_479_p3.read();
    }
    if ((!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_reg_645.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        dot_reg_670 = grp_fu_321_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_372_p2.read()) || 
  !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_565.read())))) {
        i_reg_624 = i_fu_413_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        nonZeroFeature_load_reg_560 = nonZeroFeature_q0.read();
        tmp_2_reg_565 = tmp_2_fu_345_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        p1_2_reg_655 = p1_2_fu_525_p3.read();
        p2_2_reg_660 = p2_2_fu_533_p3.read();
        tmp_7_reg_645 = tmp_7_fu_487_p2.read();
        weight_load_reg_650 = weight_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        temp_reg_680 = temp_fu_313_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_565.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_372_p2.read()))) {
        tmp_11_reg_577 = tmp_11_fu_387_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_345_p2.read()))) {
        tmp_3_cast_reg_569 = tmp_3_cast_fu_357_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_7_reg_645.read()))) {
        tmp_9_reg_665 = grp_fu_326_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_fu_330_p2.read(), ap_const_lv1_0))) {
        tmp_reg_550 = tmp_fu_336_p1.read();
    }
}

void synth_top_classifyLinear::thread_a2_fu_450_p3() {
    a2_fu_450_p3 = (!sel_tmp4_fu_445_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_fu_445_p2.read()[0].to_bool())? example_2_id_q0.read(): sel_tmp3_fu_437_p3.read());
}

void synth_top_classifyLinear::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond_fu_330_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond_fu_330_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_bdd_106() {
    ap_sig_bdd_106 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_120() {
    ap_sig_bdd_120 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_135() {
    ap_sig_bdd_135 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_171() {
    ap_sig_bdd_171 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_184() {
    ap_sig_bdd_184 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_198() {
    ap_sig_bdd_198 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_210() {
    ap_sig_bdd_210 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_220() {
    ap_sig_bdd_220 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_229() {
    ap_sig_bdd_229 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_242() {
    ap_sig_bdd_242 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_271() {
    ap_sig_bdd_271 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_280() {
    ap_sig_bdd_280 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void synth_top_classifyLinear::thread_ap_sig_bdd_38() {
    ap_sig_bdd_38 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_bdd_198.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_bdd_271.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_bdd_210.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_bdd_220.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_bdd_229.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_38.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_bdd_242.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_106.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_120.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_135.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_171.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_184.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_280.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_dot_1_fu_541_p3() {
    dot_1_fu_541_p3 = (!tmp_7_reg_645.read()[0].is_01())? sc_lv<64>(): ((tmp_7_reg_645.read()[0].to_bool())? dot_reg_670.read(): dot_0_i_reg_288.read());
}

void synth_top_classifyLinear::thread_example_0_id_address0() {
    example_0_id_address0 =  (sc_lv<10>) (tmp_6_fu_401_p1.read());
}

void synth_top_classifyLinear::thread_example_0_id_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        example_0_id_ce0 = ap_const_logic_1;
    } else {
        example_0_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_example_0_value_address0() {
    example_0_value_address0 =  (sc_lv<10>) (tmp_6_fu_401_p1.read());
}

void synth_top_classifyLinear::thread_example_0_value_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        example_0_value_ce0 = ap_const_logic_1;
    } else {
        example_0_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_example_1_id_address0() {
    example_1_id_address0 =  (sc_lv<10>) (tmp_6_fu_401_p1.read());
}

void synth_top_classifyLinear::thread_example_1_id_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        example_1_id_ce0 = ap_const_logic_1;
    } else {
        example_1_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_example_1_value_address0() {
    example_1_value_address0 =  (sc_lv<10>) (tmp_6_fu_401_p1.read());
}

void synth_top_classifyLinear::thread_example_1_value_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        example_1_value_ce0 = ap_const_logic_1;
    } else {
        example_1_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_example_2_id_address0() {
    example_2_id_address0 =  (sc_lv<10>) (tmp_6_fu_401_p1.read());
}

void synth_top_classifyLinear::thread_example_2_id_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        example_2_id_ce0 = ap_const_logic_1;
    } else {
        example_2_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_example_2_value_address0() {
    example_2_value_address0 =  (sc_lv<10>) (tmp_6_fu_401_p1.read());
}

void synth_top_classifyLinear::thread_example_2_value_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        example_2_value_ce0 = ap_const_logic_1;
    } else {
        example_2_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_example_3_id_address0() {
    example_3_id_address0 =  (sc_lv<10>) (tmp_6_fu_401_p1.read());
}

void synth_top_classifyLinear::thread_example_3_id_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        example_3_id_ce0 = ap_const_logic_1;
    } else {
        example_3_id_ce0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_example_3_value_address0() {
    example_3_value_address0 =  (sc_lv<10>) (tmp_6_fu_401_p1.read());
}

void synth_top_classifyLinear::thread_example_3_value_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        example_3_value_ce0 = ap_const_logic_1;
    } else {
        example_3_value_ce0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_example_value_load_phi_fu_479_p3() {
    example_value_load_phi_fu_479_p3 = (!sel_tmp4_fu_445_p2.read()[0].is_01())? sc_lv<64>(): ((sel_tmp4_fu_445_p2.read()[0].to_bool())? example_2_value_q0.read(): sel_tmp9_fu_471_p3.read());
}

void synth_top_classifyLinear::thread_exitcond_fu_330_p2() {
    exitcond_fu_330_p2 = (!yindex_assign_reg_252.read().is_01() || !ap_const_lv6_33.is_01())? sc_lv<1>(): sc_lv<1>(yindex_assign_reg_252.read() == ap_const_lv6_33);
}

void synth_top_classifyLinear::thread_grp_fu_321_ce() {
    grp_fu_321_ce = ap_const_logic_1;
}

void synth_top_classifyLinear::thread_grp_fu_321_p0() {
    grp_fu_321_p0 = dot_0_i_reg_288.read();
}

void synth_top_classifyLinear::thread_grp_fu_321_p1() {
    grp_fu_321_p1 = tmp_9_reg_665.read();
}

void synth_top_classifyLinear::thread_grp_fu_326_ce() {
    grp_fu_326_ce = ap_const_logic_1;
}

void synth_top_classifyLinear::thread_grp_fu_326_p0() {
    grp_fu_326_p0 = weight_load_reg_650.read();
}

void synth_top_classifyLinear::thread_grp_fu_326_p1() {
    grp_fu_326_p1 = example_value_load_phi_reg_640.read();
}

void synth_top_classifyLinear::thread_i_fu_413_p2() {
    i_fu_413_p2 = (!yindex_assign_reg_252.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(yindex_assign_reg_252.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void synth_top_classifyLinear::thread_nonZeroFeature_address0() {
    nonZeroFeature_address0 =  (sc_lv<6>) (tmp_fu_336_p1.read());
}

void synth_top_classifyLinear::thread_nonZeroFeature_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        nonZeroFeature_ce0 = ap_const_logic_1;
    } else {
        nonZeroFeature_ce0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_not_i_fu_366_p2() {
    not_i_fu_366_p2 = (!p1_0_i_reg_264.read().is_01() || !ap_const_lv32_33.is_01())? sc_lv<1>(): (sc_bigint<32>(p1_0_i_reg_264.read()) < sc_bigint<32>(ap_const_lv32_33));
}

void synth_top_classifyLinear::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<6>) (tmp_reg_550.read());
}

void synth_top_classifyLinear::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_output_r_d0() {
    output_r_d0 = tmp_1_fu_317_p1.read();
}

void synth_top_classifyLinear::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_p1_1_fu_509_p3() {
    p1_1_fu_509_p3 = (!tmp_s_fu_492_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_s_fu_492_p2.read()[0].to_bool())? p1_0_i_reg_264.read(): p1_fu_503_p2.read());
}

void synth_top_classifyLinear::thread_p1_2_fu_525_p3() {
    p1_2_fu_525_p3 = (!tmp_7_fu_487_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_7_fu_487_p2.read()[0].to_bool())? p1_fu_503_p2.read(): p1_1_fu_509_p3.read());
}

void synth_top_classifyLinear::thread_p1_fu_503_p2() {
    p1_fu_503_p2 = (!ap_const_lv32_1.is_01() || !p1_0_i_reg_264.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(p1_0_i_reg_264.read()));
}

void synth_top_classifyLinear::thread_p2_1_fu_517_p3() {
    p2_1_fu_517_p3 = (!tmp_s_fu_492_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_s_fu_492_p2.read()[0].to_bool())? p2_fu_497_p2.read(): p2_0_i_reg_276.read());
}

void synth_top_classifyLinear::thread_p2_2_fu_533_p3() {
    p2_2_fu_533_p3 = (!tmp_7_fu_487_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_7_fu_487_p2.read()[0].to_bool())? p2_fu_497_p2.read(): p2_1_fu_517_p3.read());
}

void synth_top_classifyLinear::thread_p2_fu_497_p2() {
    p2_fu_497_p2 = (!ap_const_lv32_1.is_01() || !p2_0_i_reg_276.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(p2_0_i_reg_276.read()));
}

void synth_top_classifyLinear::thread_p_sum_i_fu_382_p2() {
    p_sum_i_fu_382_p2 = (!tmp_3_cast_reg_569.read().is_01() || !tmp_6_cast_fu_378_p1.read().is_01())? sc_lv<33>(): (sc_biguint<33>(tmp_3_cast_reg_569.read()) + sc_bigint<33>(tmp_6_cast_fu_378_p1.read()));
}

void synth_top_classifyLinear::thread_sel_tmp1_fu_424_p3() {
    sel_tmp1_fu_424_p3 = (!sel_tmp_fu_419_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_fu_419_p2.read()[0].to_bool())? example_0_id_q0.read(): example_3_id_q0.read());
}

void synth_top_classifyLinear::thread_sel_tmp2_fu_432_p2() {
    sel_tmp2_fu_432_p2 = (!tmp_11_reg_577.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_11_reg_577.read() == ap_const_lv2_1);
}

void synth_top_classifyLinear::thread_sel_tmp3_fu_437_p3() {
    sel_tmp3_fu_437_p3 = (!sel_tmp2_fu_432_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp2_fu_432_p2.read()[0].to_bool())? example_1_id_q0.read(): sel_tmp1_fu_424_p3.read());
}

void synth_top_classifyLinear::thread_sel_tmp4_fu_445_p2() {
    sel_tmp4_fu_445_p2 = (!tmp_11_reg_577.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(tmp_11_reg_577.read() == ap_const_lv2_2);
}

void synth_top_classifyLinear::thread_sel_tmp7_fu_463_p3() {
    sel_tmp7_fu_463_p3 = (!sel_tmp_fu_419_p2.read()[0].is_01())? sc_lv<64>(): ((sel_tmp_fu_419_p2.read()[0].to_bool())? example_0_value_q0.read(): example_3_value_q0.read());
}

void synth_top_classifyLinear::thread_sel_tmp9_fu_471_p3() {
    sel_tmp9_fu_471_p3 = (!sel_tmp2_fu_432_p2.read()[0].is_01())? sc_lv<64>(): ((sel_tmp2_fu_432_p2.read()[0].to_bool())? example_1_value_q0.read(): sel_tmp7_fu_463_p3.read());
}

void synth_top_classifyLinear::thread_sel_tmp_fu_419_p2() {
    sel_tmp_fu_419_p2 = (!tmp_11_reg_577.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_11_reg_577.read() == ap_const_lv2_0);
}

void synth_top_classifyLinear::thread_temp_fu_313_p0() {
    temp_fu_313_p0 = p_0_i_reg_300.read();
}

void synth_top_classifyLinear::thread_tmp_10_fu_391_p4() {
    tmp_10_fu_391_p4 = p_sum_i_fu_382_p2.read().range(6, 2);
}

void synth_top_classifyLinear::thread_tmp_11_fu_387_p1() {
    tmp_11_fu_387_p1 = p_sum_i_fu_382_p2.read().range(2-1, 0);
}

void synth_top_classifyLinear::thread_tmp_1_fu_317_p0() {
    tmp_1_fu_317_p0 = temp_reg_680.read();
}

void synth_top_classifyLinear::thread_tmp_2_fu_345_p2() {
    tmp_2_fu_345_p2 = (!nonZeroFeature_q0.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(nonZeroFeature_q0.read() == ap_const_lv32_0);
}

void synth_top_classifyLinear::thread_tmp_3_cast_fu_357_p1() {
    tmp_3_cast_fu_357_p1 = esl_zext<33,13>(tmp_3_fu_351_p2.read());
}

void synth_top_classifyLinear::thread_tmp_3_fu_351_p0() {
    tmp_3_fu_351_p0 =  (sc_lv<6>) (tmp_3_fu_351_p00.read());
}

void synth_top_classifyLinear::thread_tmp_3_fu_351_p00() {
    tmp_3_fu_351_p00 = esl_zext<13,6>(yindex_assign_reg_252.read());
}

void synth_top_classifyLinear::thread_tmp_3_fu_351_p2() {
    tmp_3_fu_351_p2 = (!tmp_3_fu_351_p0.read().is_01() || !ap_const_lv13_32.is_01())? sc_lv<13>(): sc_biguint<6>(tmp_3_fu_351_p0.read()) * sc_biguint<13>(ap_const_lv13_32);
}

void synth_top_classifyLinear::thread_tmp_4_fu_361_p2() {
    tmp_4_fu_361_p2 = (!p2_0_i_reg_276.read().is_01() || !nonZeroFeature_load_reg_560.read().is_01())? sc_lv<1>(): (sc_bigint<32>(p2_0_i_reg_276.read()) < sc_bigint<32>(nonZeroFeature_load_reg_560.read()));
}

void synth_top_classifyLinear::thread_tmp_5_fu_372_p2() {
    tmp_5_fu_372_p2 = (tmp_4_fu_361_p2.read() & not_i_fu_366_p2.read());
}

void synth_top_classifyLinear::thread_tmp_6_cast_fu_378_p1() {
    tmp_6_cast_fu_378_p1 = esl_sext<33,32>(p2_0_i_reg_276.read());
}

void synth_top_classifyLinear::thread_tmp_6_fu_401_p1() {
    tmp_6_fu_401_p1 = esl_sext<64,5>(tmp_10_fu_391_p4.read());
}

void synth_top_classifyLinear::thread_tmp_7_fu_487_p2() {
    tmp_7_fu_487_p2 = (!p1_0_i_reg_264.read().is_01() || !a2_reg_629.read().is_01())? sc_lv<1>(): sc_lv<1>(p1_0_i_reg_264.read() == a2_reg_629.read());
}

void synth_top_classifyLinear::thread_tmp_8_fu_458_p1() {
    tmp_8_fu_458_p1 = esl_sext<64,32>(p1_0_i_reg_264.read());
}

void synth_top_classifyLinear::thread_tmp_fu_336_p1() {
    tmp_fu_336_p1 = esl_zext<64,6>(yindex_assign_reg_252.read());
}

void synth_top_classifyLinear::thread_tmp_s_fu_492_p2() {
    tmp_s_fu_492_p2 = (!p1_0_i_reg_264.read().is_01() || !a2_reg_629.read().is_01())? sc_lv<1>(): (sc_bigint<32>(p1_0_i_reg_264.read()) > sc_bigint<32>(a2_reg_629.read()));
}

void synth_top_classifyLinear::thread_weight_address0() {
    weight_address0 =  (sc_lv<6>) (tmp_8_fu_458_p1.read());
}

void synth_top_classifyLinear::thread_weight_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        weight_ce0 = ap_const_logic_1;
    } else {
        weight_ce0 = ap_const_logic_0;
    }
}

void synth_top_classifyLinear::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond_fu_330_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_372_p2.read()) || !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_565.read()))) {
                ap_NS_fsm = ap_ST_st19_fsm_18;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXX";
            break;
    }
}

}

